/**
 * `.agent/.tool/*.md` 正文由本模块按 `WORKSPACE_CAPABILITY_TOOL_NAMES` 自动生成，与引擎注册的工具名保持同步。
 * 修改能力清单请改 `workspace-tool-manifest-bridge.ts`，勿手写分裂列表。
 */

import { WORKSPACE_CAPABILITY_TOOL_NAMES, WORKSPACE_TOOLS_ALWAYS_ALLOWED } from './workspace-tool-manifest-bridge';

function bulletTools(names: readonly string[]): string {
  return names.map((n) => `- \`${n}\``).join('\n');
}

/** `.agent/.tool/docs.md` */
export function buildWorkspaceToolDocsMd(): string {
  return [
    `# 文档读写能力（docs）`,
    ``,
    `## 是什么`,
    ``,
    `这是一组「对工作区文件/目录进行读取与写入」的模型工具。它们受工作区沙箱约束，只能在当前工作区内操作。`,
    ``,
    `> 开关：\`.agent/.tool/manifest.json\` → \`tools.docs\``,
    ``,
    `## 有什么用`,
    ``,
    `- 在对话中落地修改：创建/更新文件、批量替换、补丁式修改`,
    `- 辅助理解代码：读取文件片段、预览目录结构（与后续工具/实现配合）`,
    `- 形成可追溯交付：把“想法”写成 PRD/README/脚本/配置并落盘`,
    ``,
    `## 该怎么用`,
    ``,
    `- **优先只读后写**：先读取相关文件确认现状，再进行写入/补丁。`,
    `- **小步提交**：一次改动尽量聚焦一个目的，便于回滚与评审。`,
    `- **严格遵守路径边界**：所有路径必须在工作区根目录下。`,
    ``,
    `典型流程：`,
    `1) \`workspace_list_dir\` 找到目标文件`,
    `2) \`workspace_read_file_preview\` / \`workspace_read_file\` 确认上下文`,
    `3) \`workspace_apply_patch\` 做最小改动（或 \`workspace_write_file\` 新建/大段生成）`,
    ``,
    `## 什么时候用`,
    ``,
    `- 需要**真实落地交付**（代码/文档/配置）时`,
    `- 需要从项目文件中取证、核对真实实现时`,
    `- 需要把输出保存为资产（例如模板、脚本、规范）时`,
    ``,
    `## 支持的格式（读取 / 侧栏预览 / 工具读取）`,
    ``,
    `以下为应用侧对「读文件 / 预览」的增强能力；超出范围时按**纯文本尝试解码**或标记为**不可预览二进制**。单文件体积另有上限（图片、Office/PDF 等分别限制，过大将拒绝预览）。`,
    ``,
    `| 类型 | 扩展名 / 说明 | 行为概要 |`,
    `| --- | --- | --- |`,
    `| 纯文本与源码 | 无扩展名限制，按内容解码 | 以 UTF-8 为主尝试预览；过大截断。工具 \`workspace_read_file\` 按行范围读取文本。 |`,
    `| Markdown | \`.md\`、\`.markdown\` | 侧栏可切换「渲染预览 / 源码」。 |`,
    `| 图片 | \`.png\` \`.jpg\` \`.jpeg\` \`.gif\` \`.webp\` \`.bmp\` \`.svg\` \`.ico\` \`.avif\` \`.tif\` \`.tiff\` | 侧栏内嵌图片预览（超过体积上限则拒绝）。工具预览对图片仅返回短标记，不内联整段 Base64。 |`,
    `| Excel | \`.xlsx\` \`.xls\` \`.xlsm\` \`.ods\` | 解析为**多工作表、制表符分隔的文本摘要**（行数/字符有上限）。\`workspace_read_file\` 对同扩展名返回提取后的纯文本再按行切片。 |`,
    `| PDF | \`.pdf\` | 侧栏用 **PDF.js 画布**渲染版式；另抽取**文字层**供折叠查看。\`workspace_read_file_preview\` 返回 JSON（页数、\`text_extract\` 等）；无文字层的扫描件可能正文为空。\`workspace_read_file\` 返回前若干页的提取文本再按行切片。 |`,
    `| CSV | \`.csv\` | 侧栏用 **Papa Parse** 渲染为**表格**（最多展示约 **500** 行；解析失败则退回纯文本）。 |`,
    `| 其他二进制 | — | 侧栏提示不可预览；工具读取仍可能得到乱码或需换用专用流程。 |`,
    ``,
    `**写入（\`workspace_write_file\` 等）**：以 **UTF-8 文本**为主；不保证直接写入二进制或 Office/PDF 原生格式（需通过脚本/外部工具生成）。`,
    ``,
    `## 工具清单（受 tools.docs 关断）`,
    ``,
    `下列 **模型工具** 受 manifest 中 \`tools.docs\` 关断：`,
    ``,
    bulletTools(WORKSPACE_CAPABILITY_TOOL_NAMES.docs),
    ``,
    `> 轻量工具 ${WORKSPACE_TOOLS_ALWAYS_ALLOWED.map((n) => `\`${n}\``).join('、')} 始终可用，不参与能力关断。`,
    ``,
    `提示：破坏性/高风险写入（例如删除、覆盖关键文件）会触发审批策略或需要明确确认。`,
    ``,
  ].join('\n');
}

/** `.agent/.tool/browser.md` —— 网络搜索 / 爬取 / 内嵌打开 分项关断 */
export function buildWorkspaceToolBrowserMd(): string {
  return [
    `# 网络与页面能力（browser）`,
    ``,
    `## 是什么`,
    ``,
    `用于访问外部网站/页面的工具集合，分为：**搜索**、**爬取（抽取文本）**、**在应用内打开页面**。`,
    ``,
    `> 开关：\`.agent/.tool/manifest.json\` → \`tools.web_search\` / \`tools.web_scrape\` / \`tools.embedded_browser\`（彼此独立）`,
    ``,
    `## 有什么用`,
    ``,
    `- 获取项目外的最新信息（搜索）`,
    `- 把网页内容抽成可被模型处理的纯文本（爬取）`,
    `- 让用户在应用右侧直接打开页面进行人工确认（内嵌打开）`,
    ``,
    `## 该怎么用`,
    ``,
    `- **查信息优先用 \`web_search\`**（快、结构化结果）`,
    `- **需要正文细节再用 \`web_scrape\`**（会保存到 \`.agent/.clawflow/scrapes\` 并返回摘录）`,
    `- **需要人工交互/登录/动态页面**：用 \`open_embedded_browser\` 交给用户确认`,
    ``,
    `## 什么时候用`,
    ``,
    `- 需求依赖外部事实（版本、公告、API 文档、网页内容）`,
    `- 需要引用来源或复核网页原文`,
    `- 用户明确要求“打开某个网站看看”`,
    ``,
    `以下三类能力在 manifest 中 **彼此独立**（\`tools.web_search\`、\`tools.web_scrape\`、\`tools.embedded_browser\`）。`,
    ``,
    `## 网页搜索（tools.web_search）`,
    bulletTools(WORKSPACE_CAPABILITY_TOOL_NAMES.web_search),
    ``,
    `实现说明（与 OpenClaw 对齐）：**已配置 \`BRAVE_API_KEY\`（或引擎 \`webSearch.braveApiKey\`）时优先走 Brave Search API**；否则回退 **DuckDuckGo HTML 聚合**（\`html.duckduckgo.com\`，无需密钥，易受网络/限流影响）。**不是**百度站内搜索；若超时或失败，可配置代理或改用 Brave API。`,
    ``,
    `## 网络数据爬取（tools.web_scrape）`,
    bulletTools(WORKSPACE_CAPABILITY_TOOL_NAMES.web_scrape),
    ``,
    `## 应用内打开页面（tools.embedded_browser）`,
    bulletTools(WORKSPACE_CAPABILITY_TOOL_NAMES.embedded_browser),
    ``,
    `> 说明：\`web_scrape\` 当前为主进程 HTTP 拉取并解析 HTML（不执行页面 JS）；与侧栏内嵌 WebView 为不同链路。`,
    `> 网络失败时会返回可诊断的 \`errorCode\` 与 \`hint\`，并支持 \`HTTP_PROXY/HTTPS_PROXY/NO_PROXY\`。`,
    ``,
  ].join('\n');
}

/** `.agent/.tool/git.md` */
export function buildWorkspaceToolGitMd(): string {
  return [
    `# Git 操作能力（git）`,
    ``,
    `## 是什么`,
    ``,
    `用于在当前工作区内执行受控的 Git 操作（只读/对比/日志等）。具体可用命令以工具清单为准。`,
    ``,
    `> 开关：\`.agent/.tool/manifest.json\` → \`tools.git\``,
    ``,
    `## 有什么用`,
    ``,
    `- 查看当前改动（status/diff）`,
    `- 回溯提交历史（log）`,
    `- 辅助生成可评审的变更说明与提交信息`,
    ``,
    `## 该怎么用`,
    ``,
    `- 先 \`workspace_git_status\` 确认改动范围`,
    `- 再 \`workspace_git_diff\` 查看细节（必要时 staged/unstaged）`,
    `- 用 \`workspace_git_log\` 对齐仓库提交风格`,
    ``,
    `## 什么时候用`,
    ``,
    `- 你要提交/推送前`,
    `- 你需要解释“改了什么/为什么改”`,
    `- 你需要定位某段代码何时引入`,
    ``,
    `下列工具受 \`tools.git\` 关断：`,
    ``,
    bulletTools(WORKSPACE_CAPABILITY_TOOL_NAMES.git),
    ``,
    `提示：提交/推送属于高影响操作，通常需要用户明确指示或审批通过。`,
    ``,
  ].join('\n');
}

/** `.agent/.tool/todos.md` */
export function buildWorkspaceToolTodosMd(): string {
  return [
    `# 待办与调度（todos）`,
    ``,
    `## 是什么`,
    ``,
    `**自动待办 / 调度**是工作区内的**纯功能性**能力：创建、更新、删除「到点触发」的 todo trigger，由主进程在指定时间或间隔把**简短指令**写回会话并驱动后续处理。`,
    ``,
    `它是“**把一件明确的事，钉到时间表上**”：无人格、不做多轮澄清，也不替你拆解复杂项目；只负责**时间表 + 任务登记 + 状态跟踪**。`,
    ``,
    `> 开关：\`.agent/.tool/manifest.json\` → \`tools.todos\``,
    ``,
    `## 工具使用范围（能做 / 不能做）`,
    ``,
    `**能做**（范围内的事）`,
    ``,
    `- 创建一条「到点触发」或「周期触发」的待办（todo trigger）`,
    `- 更新待办的：标题/指令文本、触发时间/周期、是否启用、备注、状态等元数据`,
    `- 删除待办；或临时停用再启用`,
    `- 到点后由主进程把“触发指令”写回会话（可选：触发后自动提交给模型继续处理）`,
    ``,
    `**不能做**（超出范围的事）`,
    ``,
    `- **不会**替你执行复杂任务：不做调研/写代码/跑命令/改文件（执行仍由主会话或子 Agent 完成）`,
    `- **不会**把一串待办当作“项目计划”自动拆分、排期与验收`,
    `- **不会**进行多轮澄清：如果指令不清晰，到点只会把原指令原样写回会话`,
    ``,
    `> 实践原则：把 trigger 的文本写成“一句话就能执行/判断”的短指令；不要把含糊的大块工作塞进待办里。`,
    ``,
    `## 有什么用`,
    ``,
    `- 定时提醒、间隔执行「写入对话 / 触发模型继续处理」`,
    `- 周期性工作钉在时间表上（如每日检查、每周汇总）`,
    ``,
    `## 该怎么用`,
    ``,
    `- 使用工具：\`workspace_todo_create\` / \`workspace_todo_update\` / \`workspace_todo_remove\`（以及列表/查看相关工具）`,
    `- 数据落盘：\`.agent/.clawflow/\`（创建/修改后会刷新侧栏待办，并与主进程调度对齐）`,
    ``,
    `### 写对“指令文本”（最重要）`,
    ``,
    `到点触发时，系统写回会话的就是这段文本。要求：**短、明确、可执行、可验收**。`,
    ``,
    `好的例子：`,
    ``,
    `- 「今天 17:30 前，把 PR #123 的 CI 失败项跑一遍并贴回失败原因」`,
    `- 「每周一 10:00，检查账单异常（>20%）并写一段结论」`,
    `- 「明天 09:00，提醒我把版本号从 1.2.3 升到 1.2.4 并打 tag」`,
    ``,
    `不好的例子：`,
    ``,
    `- 「把这个项目做完」`,
    `- 「研究一下怎么优化性能」`,
    ``,
    `### 触发方式（何时触发）`,
    ``,
    `- 一次性：在某个时间点触发一次（适合“某天提醒/截止前复核”）`,
    `- 周期性：按间隔或周期触发（适合“每天检查/每周汇总”）`,
    `- Cron 定点：用 cron 表达式指定“每周/每月/工作日”等定点触发（适合“每周一 10 点例会提醒”）`,
    ``,
    `### 触发后行为（写回会话 / 是否自动继续）`,
    ``,
    `- 写回会话：到点把指令写回当前工作区的会话（用于提醒/留下记录）`,
    `- 可选自动继续：如果创建时选择“触发后自动提交给模型”，则到点会把该指令当作用户输入继续处理`,
    ``,
    `## 什么时候用`,
    ``,
    `- 任务**已经能写成一条清晰指令**，且需要**未来某时刻或周期**自动再出现`,
    `- 不需要「像同事一样」包办实施，只需要**钉住时间与状态**`,
    ``,
    `下列工具受 \`tools.todos\` 关断：`,
    ``,
    bulletTools(WORKSPACE_CAPABILITY_TOOL_NAMES.todos),
    ``,
  ].join('\n');
}

/** `.agent/.tool/subagents.md` */
export function buildWorkspaceToolSubagentsMd(): string {
  return [
    `# 子 Agent 槽位（subagents）`,
    ``,
    `## 是什么`,
    ``,
    `**子 Agent** 是工作区内带**独立角色模板**的执行体（多轮对话、工具调用、结构化交付），更接近「**专才协作者**」，不是简单的待办表。`,
    ``,
    `ClawFlow 使用**固定名册**（程序 / 创意 / 数据 / 助理 + 始终占位的 Skill Agent），名称与行为摘要等元信息持久化在 \`.agent/.clawflow/sub-agents.v1.json\`。**不支持**在应用内任意新建/删除槽位；元数据可通过工具或 UI 编辑。`,
    ``,
    `> 开关：\`.agent/.tool/manifest.json\` → \`tools.subagents\``,
    ``,
    `## 工具使用范围（能做 / 不能做）`,
    ``,
    `**能做**（范围内的事）`,
    ``,
    `- 把一段明确的工作委派给某个固定槽位（程序 / 创意 / 数据 / 助理）在后台执行`,
    `- 子 Agent 可进行多轮推理与工具调用，并将进度与最终结果**回写到主会话**`,
    `- 查看/更新子 Agent 槽位的元数据（label / behavior）用于 UI 呈现与委派说明`,
    ``,
    `**不能做**（超出范围的事）`,
    ``,
    `- **不能**新增/删除槽位 id（名册固定）`,
    `- **不能**委派或手动运行 \`cf-skill-agent\`（保留给 Hermes 技能进化流程）`,
    `- **不能保证**无副作用：如果你允许它使用写盘/执行类工具，子 Agent 可能改动文件/配置；高风险操作应在任务文本中明确约束或要求审批`,
    ``,
    `> 实践原则：把“要它交付什么”和“验收标准”写进委派文本；否则回写结果可能不可用或无法验收。`,
    ``,
    `## 该怎么用（委派方式）`,
    ``,
    `### 1) 选择槽位（固定）`,
    ``,
    `仅允许四个可委派槽位 id：\`cf-sub-program\`、\`cf-sub-creative\`、\`cf-sub-data\`、\`cf-sub-assistant\`。`,
    ``,
    `### 2) 发送委派（delegate_to_subagent）`,
    ``,
    `使用工具 **\`delegate_to_subagent\`**，传入：`,
    ``,
    `- \`slotId\`：上面四个之一`,
    `- \`taskText\`：要做的事（建议含输出格式与验收标准）`,
    `- \`conversationId\`：结果要回写到哪一个主会话`,
    ``,
    `委派后子 Agent 在**同一工作区**内异步运行；你会在主会话看到过程增量与最终结果。`,
    ``,
    `### 3) 任务文本写法（决定成败）`,
    ``,
    `推荐结构：**目标 → 范围/约束 → 输出格式 → 验收标准**。`,
    ``,
    `好的例子：`,
    ``,
    `- 「用程序槽位修复 Settings 页面崩溃：只改前端；给出根因、改动点、以及如何手测。输出：3 条 bullet + 关键 diff 路径」`,
    `- 「用数据槽位分析 logs.jsonl：找出 top 5 错误类型与出现频率，输出一段结论 + 下一步建议」`,
    ``,
    `不好的例子：`,
    ``,
    `- 「帮我优化一下」`,
    `- 「把这个项目弄好」`,
    ``,
    `### 4) 明确禁止项（可选但推荐）`,
    ``,
    `如果你不希望产生某类副作用，请在 \`taskText\` 里写清：例如“不要改配置/不要删文件/不要提交 git”。`,
    ``,
    `> 禁止：向 \`delegate_to_subagent\` 传入 **\`cf-skill-agent\`**。Skill Agent 仅用于 Hermes 技能进化，由系统在启用 \`tools.skills\` 时单独调度。`,
    ``,
    `## 子 Agent 根目录（.subagent/）`,
    ``,
    `工作区根下 **\`.subagent/\`** 集中子 Agent 相关数据，与主 **\`.agent/\`** 并列：`,
    ``,
    `- **\`.subagent/.subclawflow/<槽位 id>/\`**：各槽位**工作缓存**（中间产物、草稿等）。`,
    `- **\`.subagent/.submemory/<槽位 id>/\`**：各槽位**独立记忆**（片段笔记、可选 \`MEMORY.md\`）。`,
    `- **\`.subagent/.subroleAgent/<模板 id>/\`**：各槽位**角色模板**（\`AGENTS.md\` / \`SOUL.md\` / \`TOOLS.md\` 等，可覆盖）。`,
    ``,
    `主会话对话、待办触发器、子 Agent 名册 JSON、爬取与 Hermes DB 等在 **\`.agent/.clawflow/\`**。初始化工作区时会创建 \`.subagent/\` 下上述子目录及固定名册对应槽位文件夹。`,
    ``,
    `## 元数据与 UI`,
    ``,
    `- **\`workspace_subagent_list\` / \`workspace_subagent_upsert\`**：查看或更新固定槽位的 label / behavior（id 不可随意新增）。`,
    `- **\`workspace_subagent_remove\`**：已禁用（名册固定）。`,
    `- 应用内「子 Agent」面板可查看状态、编辑摘要；Skill Agent 的「运行」由系统负责，不在此手动触发。`,
    ``,
    `## 什么时候用`,
    ``,
    `- 任务需要**多步骤**、需要某一类“专才视角”（程序/创意/数据/推进）`,
    `- 你希望它在后台推进，并在主会话里持续回写进度与最终结论`,
    `- 你的任务描述已经足够具体（至少能写清输出格式与验收标准）`,
    ``,
    `下列工具受 \`tools.subagents\` 关断：`,
    ``,
    bulletTools(WORKSPACE_CAPABILITY_TOOL_NAMES.subagents),
    ``,
  ].join('\n');
}

/** `.agent/.tool/skills.md` — Hermes 式工作区技能（`.agent/.skills`） */
export function buildWorkspaceToolSkillsMd(): string {
  return [
    `# 技能（Skills，Hermes 式工作区技能）`,
    ``,
    `## 是什么`,
    ``,
    `工作区技能存放在 **\`.agent/.skills/<名称>/\`**，主文件为 **\`SKILL.md\`**，可选 **\`references/\`** 下放补充 \`.md\` / \`.txt\`。由应用内 FTS 索引与 UI 只读浏览；**不提供** OpenClaw CLI 技能市场。`,
    ``,
    `> 首次初始化且尚无任何技能时，会自动创建示例 **\`.agent/.skills/default/SKILL.md\`**，便于面板与检索立刻可见。`,
    ``,
    `> 开关：\`.agent/.tool/manifest.json\` → \`tools.skills\`（仅影响下列 **只读** 模型工具；浏览技能请用应用内「技能」面板）`,
    ``,
    `## 模型工具（只读）`,
    ``,
    bulletTools(WORKSPACE_CAPABILITY_TOOL_NAMES.skills),
    ``,
  ].join('\n');
}

/** `.agent/.tool/knowledge_base.md` */
export function buildWorkspaceToolKnowledgeBaseMd(): string {
  return [
    `# 知识库（knowledge_base，占位）`,
    ``,
    `## 是什么`,
    ``,
    `面向未来的“工作区知识库/检索”能力入口（RAG / 向量索引 / 路径索引等）。目前为占位实现。`,
    ``,
    `> 开关：\`.agent/.tool/manifest.json\` → \`tools.knowledge_base\``,
    ``,
    `## 有什么用`,
    ``,
    `- 未来用于把项目内资料做索引后可检索（比全文搜索更语义化）`,
    ``,
    `## 该怎么用`,
    ``,
    `- 当前仅用于接口占位与权限开关；后续会补全数据模型与 retriever`,
    ``,
    `## 什么时候用`,
    ``,
    `- 当你希望“问项目资料”而不是“搜索文本”时（未来能力）`,
    ``,
    `下列工具受 \`tools.knowledge_base\` 关断。当前为占位实现，后续可接向量索引与 RAG 管道：`,
    ``,
    bulletTools(WORKSPACE_CAPABILITY_TOOL_NAMES.knowledge_base),
    ``,
  ].join('\n');
}
