import { app, BrowserWindow, Menu, ipcMain, shell, clipboard, screen } from 'electron';
import * as path from 'path';
import * as fs from 'fs';
import {
  registerOpenClawIPC,
  setActiveWorkspaceRoot,
  getActiveWorkspaceRoot,
  getGlobalOpenClawCliEngine,
} from './engine/openclaw-engine';
import { registerClawFlowIPC, syncClawFlowEngineWorkspaceRoot } from './engine/clawflow-engine';
import { getGatewayDaemon, registerGatewayIPC } from './engine/gateway-daemon';
import * as workspaceService from './workspace-service';
import * as workspaceExplorer from './workspace-explorer';
import * as workspaceChangeLog from './workspace-change-log';
import type { WorkspaceToolSelection } from './shared/workspace-tools';
import { resolveWorkspaceRootForWebContents } from './electron-workspace-context';
import { stickySatellitePathByWindowId } from './sticky-satellite-windows';
import { getMainShellLastWorkspacePath, setMainShellLastWorkspacePath } from './main-shell-workspace';
import { readTodoTriggers, writeTodoTriggers } from './todo-triggers-service';
import { broadcastTodoTriggersUpdated } from './todo-triggers-broadcast';
import { readSubAgentSlots, writeSubAgentSlots, coerceSubAgentSlotsPayload } from './sub-agent-service';
import { broadcastSubAgentsUpdated } from './sub-agent-broadcast';
import { runSubAgentOnce, sendSubAgentRunDelta, sendSubAgentRunFinal } from './sub-agent-runner';
import { mergeSubAgentSlotsAfterEditorSave, ensureSubAgentRosterForWorkspace } from './sub-agent-roster-bootstrap';
import { SKILL_AGENT_SLOT_ID } from './shared/skill-agent-constants';
import { readScrapeJobs } from './scrape-service';
import { rescheduleAllTodoTriggers, rescheduleTodoTriggersForWorkspace } from './todo-triggers-scheduler';
import { rebuildHermesSkillFtsIndex, searchHermesMemory } from './engine/hermes-memory-db';
import { listWorkspaceHermesSkills, readWorkspaceSkillTextFile } from './workspace-skills-read';
import { readDisabledSkillRootsSync, setSkillRootEnabled } from './workspace-skills-ui-state';
import { deleteHermesSkillDirectory } from './workspace-skills-delete';
import { reconcileRunSnapshotsAfterRestart, readRunSnapshots } from './sub-agent-run-snapshot';
import { gitCloneWorkspace, gitPullWorkspace, gitPushWorkspace } from './workspace-git';
import type { TodoTriggerRecord } from './shared/todo-triggers';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).

async function stopOpenClawGatewayBestEffort(reason: string): Promise<void> {
  const engine = getGlobalOpenClawCliEngine();
  try {
    const status = await Promise.race([
      engine.getGatewayStatus(),
      new Promise<'unknown'>((resolve) => setTimeout(() => resolve('unknown'), 1200)),
    ]);
    if (status !== 'running') return;
    await Promise.race([
      engine.stopGateway(),
      new Promise<void>((_resolve, reject) => setTimeout(() => reject(new Error('stopGateway timeout')), 8000)),
    ]);
  } catch (e: any) {
    console.warn(`[workspace] stopGateway (${reason}) failed (best-effort):`, e?.message || e);
  }
}
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

type AppLang = 'zh' | 'en';
let currentLang: AppLang = app.getLocale().toLowerCase().startsWith('zh') ? 'zh' : 'en';

/** 便签紧凑窗口：按 BrowserWindow 分别保存 bounds，支持多窗口 */
type ShellCompactState = { restoreBounds: Electron.Rectangle; restoreMaximized: boolean };
const shellCompactByWindowId = new Map<number, ShellCompactState>();

function broadcastStickyDetachedPaths(): void {
  const paths = [...new Set(stickySatellitePathByWindowId.values())];
  BrowserWindow.getAllWindows().forEach((w) => {
    if (!w.isDestroyed()) w.webContents.send('sticky:detachedPaths', { paths });
  });
  try {
    rescheduleAllTodoTriggers();
  } catch {
    /* ignore */
  }
}

/** 主壳若仍指向刚拖出到卫星的工作区，则改记到下一个可用路径并通知各窗刷新（避免主窗 UI/IPC 仍停在已分离工作区） */
function bumpMainShellWorkspaceIfSameAsSatelliteBinding(detachedResolved: string): void {
  const last = getMainShellLastWorkspacePath();
  if (!last || !workspaceService.isSameWorkspacePath(last, detachedResolved)) return;

  const reg = workspaceService.loadRegistry();
  const recent = reg.recentWorkspacePaths ?? [];
  const def = workspaceService.getDefaultWorkspacePath();
  let next: string | null = null;
  for (const p of recent) {
    if (!workspaceService.isSameWorkspacePath(p, detachedResolved)) {
      next = path.resolve(p);
      break;
    }
  }
  if (!next && !workspaceService.isSameWorkspacePath(def, detachedResolved)) {
    next = path.resolve(def);
  }
  if (!next) next = path.resolve(def);

  setMainShellLastWorkspacePath(next);
  BrowserWindow.getAllWindows().forEach((w) => {
    if (!w.isDestroyed()) w.webContents.send('workspace:changed', { path: next });
  });
}

function applyWorkspaceForFocusedWindow(win: BrowserWindow | null): void {
  if (!win || win.isDestroyed()) return;
  const sat = stickySatellitePathByWindowId.get(win.id);
  const target = sat ?? getMainShellLastWorkspacePath();
  if (!target) return;
  const cur = getActiveWorkspaceRoot();
  if (workspaceService.isSameWorkspacePath(cur, target)) return;
  workspaceService.setActiveWorkspace(target);
  setActiveWorkspaceRoot(target);
  syncClawFlowEngineWorkspaceRoot(target);
  BrowserWindow.getAllWindows().forEach((w) => {
    if (!w.isDestroyed()) w.webContents.send('workspace:changed', { path: target });
  });
}

function registerShellViewWindowIPC(): void {
  try {
    ipcMain.removeHandler('window:setShellViewAppearance');
  } catch {
    /* first load or older Electron */
  }
  ipcMain.handle('window:setShellViewAppearance', (_event, params: { compact?: boolean }) => {
    const win = BrowserWindow.fromWebContents(_event.sender);
    if (!win || win.isDestroyed()) return { ok: false as const, error: 'no_window' };
    const wantCompact = Boolean(params?.compact);

    if (wantCompact) {
      if (!shellCompactByWindowId.has(win.id)) {
        const restoreMaximized = win.isMaximized();
        if (restoreMaximized) win.unmaximize();
        const restoreBounds = win.getBounds();
        shellCompactByWindowId.set(win.id, { restoreBounds, restoreMaximized });
      }
      const wa = screen.getDisplayMatching(win.getBounds()).workArea;
      /** 便签：宽约工作区 1/4；高度为工作区高度减去上下留白（略小于整屏高度），贴右侧竖条 */
      const width = Math.max(320, Math.floor(wa.width * 0.25));
      const marginTop = 10;
      const marginBottom = 18;
      const height = Math.max(420, wa.height - marginTop - marginBottom);
      const x = wa.x + wa.width - width;
      const y = wa.y + marginTop;
      win.setMinimumSize(260, 320);
      win.setBounds({ x, y, width, height }, true);
      return { ok: true as const };
    }

    const st = shellCompactByWindowId.get(win.id);
    if (st) {
      shellCompactByWindowId.delete(win.id);
      try {
        win.setMinimumSize(0, 0);
      } catch {
        /* ignore */
      }
      win.setBounds(st.restoreBounds, true);
      if (st.restoreMaximized) win.maximize();
    }
    return { ok: true as const };
  });
}

/** 主进程一加载即注册，避免 whenReady 内前置 await 未完成时渲染进程已发起 invoke */
registerShellViewWindowIPC();

/** 外部拖入文件：须与 preload 同步，在模块加载时注册，避免 invoke 早于 registerWorkspaceIPC */
function registerWorkspaceImportExternalPathsIPC(): void {
  try {
    ipcMain.removeHandler('workspace:importExternalPaths');
  } catch {
    /* first load */
  }
  ipcMain.handle(
    'workspace:importExternalPaths',
    async (
      event,
      params: { targetRelativeDir: string; sourceAbsolutePaths: string[]; overwrite?: boolean }
    ) => {
      const root = resolveWorkspaceRootForWebContents(event.sender);
      try {
        return await workspaceExplorer.importExternalPathsIntoWorkspace(
          root,
          String(params?.targetRelativeDir ?? ''),
          Array.isArray(params?.sourceAbsolutePaths) ? params.sourceAbsolutePaths : [],
          { overwrite: params?.overwrite !== false }
        );
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : String(e);
        return { ok: false as const, error: msg };
      }
    }
  );
}
registerWorkspaceImportExternalPathsIPC();

/** 便签拖入文件夹：须在 whenReady 前可用，避免渲染进程早于 registerWorkspaceIPC 发起 invoke */
function registerWorkspaceStatAbsolutePathIPC(): void {
  try {
    ipcMain.removeHandler('workspace:statAbsolutePath');
  } catch {
    /* first load */
  }
  ipcMain.handle('workspace:statAbsolutePath', async (_e, absPath: string) => {
    const resolved = path.resolve(String(absPath || ''));
    try {
      const st = await fs.promises.stat(resolved);
      return { ok: true as const, path: resolved, isDirectory: st.isDirectory() };
    } catch {
      return { ok: false as const, error: 'not_found' as const };
    }
  });
}
registerWorkspaceStatAbsolutePathIPC();

/** 待办触发器：模块加载时注册，避免 whenReady 内 await 未完成时渲染进程已 invoke */
function registerTodoTriggersIPC(): void {
  try {
    ipcMain.removeHandler('todoTriggers:list');
  } catch {
    /* first load */
  }
  try {
    ipcMain.removeHandler('todoTriggers:saveAll');
  } catch {
    /* first load */
  }
  try {
    ipcMain.removeHandler('todoTriggers:setAiReceipt');
  } catch {
    /* first load */
  }
  ipcMain.handle('todoTriggers:list', async (event) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const triggers = await readTodoTriggers(root);
    return { triggers };
  });
  ipcMain.handle('todoTriggers:saveAll', async (event, triggers: unknown) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    if (!Array.isArray(triggers)) return { ok: false as const, error: 'invalid_payload' };
    const incoming = triggers as TodoTriggerRecord[];
    const disk = await readTodoTriggers(root);
    const diskById = new Map(disk.map((x) => [x.id, x]));
    /** 已归档条目以磁盘为准，防止渲染进程因防抖队列中的旧快照覆盖触发回执等字段 */
    const merged = incoming.map((inc) => {
      const ex = diskById.get(inc.id);
      return ex?.status === 'done' ? ex : inc;
    });
    await writeTodoTriggers(root, merged);
    rescheduleTodoTriggersForWorkspace(root);
    broadcastTodoTriggersUpdated(root);
    return { ok: true as const };
  });
  ipcMain.handle('todoTriggers:setAiReceipt', async (event, payload: unknown) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    if (!payload || typeof payload !== 'object') return { ok: false as const, error: 'invalid_payload' };
    const o = payload as Record<string, unknown>;
    const triggerId = typeof o.triggerId === 'string' ? o.triggerId.trim() : '';
    const receiptText = typeof o.receiptText === 'string' ? o.receiptText : '';
    if (!triggerId) return { ok: false as const, error: 'missing_trigger' };
    const list = await readTodoTriggers(root);
    const idx = list.findIndex((x) => x.id === triggerId);
    if (idx < 0) return { ok: false as const, error: 'not_found' };
    const now = Date.now();
    list[idx] = { ...list[idx], lastFireAiReceipt: receiptText, updatedAt: now };
    await writeTodoTriggers(root, list);
    broadcastTodoTriggersUpdated(root);
    return { ok: true as const };
  });
}
registerTodoTriggersIPC();

function registerSubAgentsIPC(): void {
  for (const ch of ['subAgents:list', 'subAgents:saveAll', 'subAgents:run'] as const) {
    try {
      ipcMain.removeHandler(ch);
    } catch {
      /* first load */
    }
  }
  ipcMain.handle('subAgents:list', async (event) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    await ensureSubAgentRosterForWorkspace(root);
    await reconcileRunSnapshotsAfterRestart(root);
    const slots = await readSubAgentSlots(root);
    const runSnapshots = await readRunSnapshots(root);
    return { slots, runSnapshots };
  });
  ipcMain.handle('subAgents:saveAll', async (event, raw: unknown) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const merged = await mergeSubAgentSlotsAfterEditorSave(root, coerceSubAgentSlotsPayload(raw));
    await writeSubAgentSlots(root, merged);
    broadcastSubAgentsUpdated(root);
    return { ok: true as const };
  });

  ipcMain.handle('subAgents:run', async (event, payload: unknown) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    if (!payload || typeof payload !== 'object') return { ok: false as const, error: 'invalid_payload' };
    const p = payload as Record<string, unknown>;
    const slotId = typeof p.slotId === 'string' ? p.slotId.trim() : '';
    const taskText = typeof p.taskText === 'string' ? p.taskText : '';
    const conversationId = typeof p.conversationId === 'string' ? p.conversationId.trim() : '';
    const modelId = typeof p.modelId === 'string' && p.modelId.trim() ? p.modelId.trim() : undefined;
    if (!slotId || !taskText || !conversationId) return { ok: false as const, error: 'missing_fields' };
    if (slotId === SKILL_AGENT_SLOT_ID) {
      return { ok: false as const, error: 'skill_agent_run_not_supported' };
    }

    const sender = event.sender;
    const res = await runSubAgentOnce({
      workspaceRoot: root,
      slotId,
      taskText,
      conversationId,
      modelId,
      onDelta: (d) => sendSubAgentRunDelta(sender, d),
      onToolApprovalNeeded: (ap) => {
        try {
          sender.send('subAgents:toolApprovalNeeded', ap);
        } catch {
          /* ignore */
        }
      },
    });

    if (res.ok) {
      sendSubAgentRunFinal(sender, { runId: res.runId, slotId, ok: true, message: res.message });
      return { ok: true as const, runId: res.runId };
    }
    sendSubAgentRunFinal(sender, { runId: res.runId, slotId, ok: false, error: res.error });
    return { ok: false as const, error: res.error, runId: res.runId };
  });
}
registerSubAgentsIPC();

function registerScrapeIPC(): void {
  for (const ch of ['scrape:listJobs', 'scrape:readArtifact'] as const) {
    try {
      ipcMain.removeHandler(ch);
    } catch {
      /* first load */
    }
  }
  ipcMain.handle('scrape:listJobs', async (event) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const jobs = await readScrapeJobs(root);
    return { jobs };
  });
  ipcMain.handle('scrape:readArtifact', async (event, payload: unknown) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const jobId =
      payload && typeof payload === 'object' && typeof (payload as { jobId?: unknown }).jobId === 'string'
        ? String((payload as { jobId: string }).jobId).trim()
        : '';
    if (!jobId) return { ok: false as const, error: 'missing_job' };
    const jobs = await readScrapeJobs(root);
    const job = jobs.find((j) => j.id === jobId);
    if (!job?.artifactRelPath || job.status !== 'ok') return { ok: false as const, error: 'no_artifact' };
    try {
      const full = workspaceExplorer.resolvePathInsideWorkspace(root, job.artifactRelPath);
      const text = await fs.promises.readFile(full, 'utf-8');
      return { ok: true as const, text };
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg };
    }
  });
}
registerScrapeIPC();

const I18N: Record<AppLang, Record<string, string>> = {
  zh: {
    file: '文件',
    edit: '编辑',
    view: '视图',
    window: '窗口',
    help: '帮助',
    about: '关于',
    services: '服务',
    hide: '隐藏',
    hideOthers: '隐藏其他',
    unhide: '显示全部',
    quit: '退出',
    undo: '撤销',
    redo: '重做',
    cut: '剪切',
    copy: '复制',
    paste: '粘贴',
    pasteAndMatchStyle: '粘贴并匹配样式',
    delete: '删除',
    selectAll: '全选',
    speech: '朗读',
    reload: '重新加载',
    forceReload: '强制重新加载',
    toggleDevTools: '切换开发者工具',
    resetZoom: '重置缩放',
    zoomIn: '放大',
    zoomOut: '缩小',
    togglefullscreen: '切换全屏',
    minimize: '最小化',
    zoom: '缩放',
    close: '关闭',
    front: '全部置于前台',
    learnMore: '了解更多',
    navChat: '对话',
    navSkills: '技能',
    navConnectors: '连接器',
    navSettings: '全局设置',
  },
  en: {
    file: 'File',
    edit: 'Edit',
    view: 'View',
    window: 'Window',
    help: 'Help',
    about: 'About',
    services: 'Services',
    hide: 'Hide',
    hideOthers: 'Hide Others',
    unhide: 'Show All',
    quit: 'Quit',
    undo: 'Undo',
    redo: 'Redo',
    cut: 'Cut',
    copy: 'Copy',
    paste: 'Paste',
    pasteAndMatchStyle: 'Paste and Match Style',
    delete: 'Delete',
    selectAll: 'Select All',
    speech: 'Speech',
    reload: 'Reload',
    forceReload: 'Force Reload',
    toggleDevTools: 'Toggle DevTools',
    resetZoom: 'Reset Zoom',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    togglefullscreen: 'Toggle Full Screen',
    minimize: 'Minimize',
    zoom: 'Zoom',
    close: 'Close',
    front: 'Bring All to Front',
    learnMore: 'Learn More',
    navChat: 'Chat',
    navSkills: 'Skills',
    navConnectors: 'Connectors',
    navSettings: 'Global settings',
  },
};

const setupApplicationMenu = () => {
  const isMac = process.platform === 'darwin';
  const nav = (path: string) => {
    const win = BrowserWindow.getAllWindows()[0];
    if (!win) return;
    win.webContents.send('app:navigate', path);
  };
  const t = (k: string) => I18N[currentLang][k] ?? k;

  const template: Electron.MenuItemConstructorOptions[] = [
    ...(isMac
      ? ([
          {
            label: app.name,
            submenu: [
              { role: 'about', label: `${t('about')} ${app.name}` },
              { type: 'separator' },
              { role: 'services', label: t('services') },
              { type: 'separator' },
              { role: 'hide', label: `${t('hide')} ${app.name}` },
              { role: 'hideOthers', label: t('hideOthers') },
              { role: 'unhide', label: t('unhide') },
              { type: 'separator' },
              { role: 'quit', label: `${t('quit')} ${app.name}` },
            ],
          },
        ] as Electron.MenuItemConstructorOptions[])
      : []),
    {
      label: t('file'),
      submenu: [
        ...(isMac
          ? ([] as Electron.MenuItemConstructorOptions[])
          : ([
              { role: 'quit', label: t('quit') },
            ] as Electron.MenuItemConstructorOptions[])),
      ],
    },
    {
      label: t('edit'),
      submenu: [
        { role: 'undo', label: t('undo') },
        { role: 'redo', label: t('redo') },
        { type: 'separator' },
        { role: 'cut', label: t('cut') },
        { role: 'copy', label: t('copy') },
        { role: 'paste', label: t('paste') },
        ...(isMac
          ? ([
              { role: 'pasteAndMatchStyle', label: t('pasteAndMatchStyle') },
              { role: 'delete', label: t('delete') },
              { role: 'selectAll', label: t('selectAll') },
              { type: 'separator' },
              { role: 'speech', label: t('speech') },
            ] as Electron.MenuItemConstructorOptions[])
          : ([
              { role: 'delete', label: t('delete') },
              { type: 'separator' },
              { role: 'selectAll', label: t('selectAll') },
            ] as Electron.MenuItemConstructorOptions[])),
      ],
    },
    {
      label: t('view'),
      submenu: [
        { label: t('navChat'), click: () => nav('/chat') },
        { label: t('navSkills'), click: () => nav('/skills') },
        { label: t('navConnectors'), click: () => nav('/connectors') },
        { label: t('navSettings'), click: () => nav('/settings') },
        { type: 'separator' },
        { role: 'reload', label: t('reload') },
        { role: 'forceReload', label: t('forceReload') },
        { role: 'toggleDevTools', label: t('toggleDevTools') },
        { type: 'separator' },
        { role: 'resetZoom', label: t('resetZoom') },
        { role: 'zoomIn', label: t('zoomIn') },
        { role: 'zoomOut', label: t('zoomOut') },
        { type: 'separator' },
        { role: 'togglefullscreen', label: t('togglefullscreen') },
      ],
    },
    {
      label: t('window'),
      role: 'window',
      submenu: [
        { role: 'minimize', label: t('minimize') },
        { role: 'zoom', label: t('zoom') },
        ...(isMac
          ? ([
              { type: 'separator' },
              { role: 'front', label: t('front') },
              { type: 'separator' },
              { role: 'window', label: t('window') },
            ] as Electron.MenuItemConstructorOptions[])
          : ([
              { role: 'close', label: t('close') },
            ] as Electron.MenuItemConstructorOptions[])),
      ],
    },
    {
      label: t('help'),
      role: 'help',
      submenu: [
        {
          label: t('learnMore'),
          click: async () => {
            const { shell } = await import('electron');
            await shell.openExternal('https://electronjs.org');
          },
        },
      ],
    },
  ];

  const menu = Menu.buildFromTemplate(template);
  Menu.setApplicationMenu(menu);
};

function registerWorkspaceIPC(): void {
  ipcMain.handle('workspace:getActive', async (event) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const meta = workspaceService.readWorkspaceMetaSync(root);
    return { path: root, meta };
  });

  ipcMain.handle('workspace:listRecent', async () => {
    return workspaceService.listRecentWorkspaceEntries();
  });

  ipcMain.handle('workspace:getDefaultPath', async () => workspaceService.getDefaultWorkspacePath());

  ipcMain.handle('workspace:remove', async (_event, folderPath: string) => {
    const res = await workspaceService.removeWorkspaceForUser(String(folderPath || ''));
    if (!res.ok) return res;
    setActiveWorkspaceRoot(res.newActivePath);
    syncClawFlowEngineWorkspaceRoot(res.newActivePath);
    BrowserWindow.getAllWindows().forEach((w) =>
      w.webContents.send('workspace:changed', { path: res.newActivePath })
    );
    await workspaceService.ensureWorkspaceInitialized(res.newActivePath);
    void stopOpenClawGatewayBestEffort('after remove');
    return res;
  });

  ipcMain.handle('workspace:setActive', async (_event, nextPath: string, opts?: { fromMainShell?: boolean }) => {
    const resolved = path.resolve(String(nextPath || ''));
    if (opts?.fromMainShell !== false) {
      setMainShellLastWorkspacePath(resolved);
    }
    workspaceService.setActiveWorkspace(resolved);
    setActiveWorkspaceRoot(resolved);
    syncClawFlowEngineWorkspaceRoot(resolved);
    BrowserWindow.getAllWindows().forEach((w) => w.webContents.send('workspace:changed', { path: resolved }));
    // 等待初始化完成（含根目录角色模板），避免 UI 已切换但文件尚未写入
    try {
      await workspaceService.ensureWorkspaceInitialized(resolved);
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      console.warn('[workspace] ensureWorkspaceInitialized failed:', msg);
    }
    void stopOpenClawGatewayBestEffort('on setActive');
    try {
      rescheduleAllTodoTriggers();
    } catch {
      /* ignore */
    }
    return { success: true, path: resolved };
  });

  /** 拖入文件夹到「+」：校验为目录后初始化并切为当前工作区 */
  ipcMain.handle('workspace:addFromAbsolutePath', async (event, absPath: string) => {
    const win = BrowserWindow.fromWebContents(event.sender);
    if (win && stickySatellitePathByWindowId.has(win.id)) {
      return { ok: false as const, error: 'satellite_no_add_workspace' };
    }
    const resolved = path.resolve(String(absPath || ''));
    let st: fs.Stats | null;
    try {
      st = await fs.promises.stat(resolved);
    } catch {
      return { ok: false as const, error: 'not_found' };
    }
    if (!st.isDirectory()) {
      return { ok: false as const, error: 'not_directory' };
    }
    try {
      await workspaceService.ensureWorkspaceInitialized(resolved);
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg };
    }
    workspaceService.setActiveWorkspace(resolved);
    setActiveWorkspaceRoot(resolved);
    syncClawFlowEngineWorkspaceRoot(resolved);
    BrowserWindow.getAllWindows().forEach((w) => w.webContents.send('workspace:changed', { path: resolved }));
    void stopOpenClawGatewayBestEffort('on addFromAbsolutePath');
    return { ok: true as const, path: resolved };
  });

  ipcMain.handle('workspace:pickFolder', async (event, opts?: { title?: string }) => {
    const win = BrowserWindow.fromWebContents(event.sender);
    if (win && stickySatellitePathByWindowId.has(win.id)) {
      return null;
    }
    const title = opts && typeof opts.title === 'string' ? opts.title : undefined;
    return await workspaceService.pickWorkspaceFolder(win, title);
  });

  ipcMain.handle(
    'workspace:ensureInitialized',
    async (_e, folderPath: string, opts?: { tools?: WorkspaceToolSelection; gitRemoteUrl?: string | null }) => {
      const meta = await workspaceService.ensureWorkspaceInitialized(String(folderPath || ''), opts);
      return { meta };
    }
  );

  ipcMain.handle(
    'workspace:gitClone',
    async (event, payload: unknown) => {
      const win = BrowserWindow.fromWebContents(event.sender);
      if (win && stickySatellitePathByWindowId.has(win.id)) {
        return { ok: false as const, error: 'satellite_no_git_clone' };
      }
      const o = payload && typeof payload === 'object' ? (payload as Record<string, unknown>) : {};
      const remoteUrl = typeof o.remoteUrl === 'string' ? o.remoteUrl.trim() : '';
      const parentDir = typeof o.parentDir === 'string' ? o.parentDir.trim() : '';
      if (!remoteUrl || !parentDir) return { ok: false as const, error: 'missing_fields' };
      return gitCloneWorkspace(remoteUrl, parentDir);
    }
  );

  ipcMain.handle('workspace:gitPull', async (_event, folderPath: string) => {
    const fp = path.resolve(String(folderPath || ''));
    if (!workspaceService.isWorkspacePathRegistered(fp)) {
      return { ok: false as const, error: 'not_registered' };
    }
    const meta = workspaceService.readWorkspaceMetaSync(fp);
    if (!meta?.gitRemoteUrl?.trim()) {
      return { ok: false as const, error: 'not_git_workspace' };
    }
    return gitPullWorkspace(fp);
  });

  ipcMain.handle('workspace:gitPush', async (_event, folderPath: string) => {
    const fp = path.resolve(String(folderPath || ''));
    if (!workspaceService.isWorkspacePathRegistered(fp)) {
      return { ok: false as const, error: 'not_registered' };
    }
    const meta = workspaceService.readWorkspaceMetaSync(fp);
    if (!meta?.gitRemoteUrl?.trim()) {
      return { ok: false as const, error: 'not_git_workspace' };
    }
    return gitPushWorkspace(fp);
  });

  ipcMain.handle('workspace:resetCache', async (event, folderPath: string) => {
    const win = BrowserWindow.fromWebContents(event.sender);
    if (win && stickySatellitePathByWindowId.has(win.id)) {
      return { ok: false as const, error: 'satellite_no_reset_cache' };
    }
    const fp = path.resolve(String(folderPath || ''));
    if (!workspaceService.isWorkspacePathRegistered(fp)) {
      return { ok: false as const, error: 'not_registered' };
    }
    const res = await workspaceService.resetWorkspaceCacheDirs(fp);
    if (!res.ok) return res;
    try {
      await workspaceService.ensureWorkspaceInitialized(fp);
    } catch {
      /* allow empty; user may want truly clean until next open */
    }
    return res;
  });

  ipcMain.handle('workspace:getToolSelection', async (_e, folderPath: string) => {
    try {
      const tools = await workspaceService.readWorkspaceToolManifest(String(folderPath || ''));
      return { ok: true as const, tools };
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg };
    }
  });

  ipcMain.handle('workspace:setToolSelection', async (_e, folderPath: string, tools: WorkspaceToolSelection) => {
    try {
      await workspaceService.writeWorkspaceToolSelection(String(folderPath || ''), tools ?? {});
      return { ok: true as const };
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg };
    }
  });

  ipcMain.handle('workspace:listDir', async (event, relativePath?: string) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    try {
      const entries = await workspaceExplorer.listWorkspaceDirectory(root, String(relativePath ?? ''));
      return { ok: true as const, entries };
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg, entries: [] as Array<{ name: string; kind: 'file' | 'dir' }> };
    }
  });

  ipcMain.handle('workspace:readFilePreview', async (event, relativePath: string) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    return await workspaceExplorer.readWorkspaceFilePreview(root, String(relativePath ?? ''));
  });

  const resolveAbs = (root: string, rel: string) => workspaceExplorer.resolvePathInsideWorkspace(root, String(rel ?? ''));

  ipcMain.handle('workspace:resolveAbsolutePath', async (event, relativePath: string) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const rel = String(relativePath ?? '');
    const abs = resolveAbs(root, rel);
    return { ok: true as const, workspaceRoot: root, relativePath: rel, absolutePath: abs };
  });

  ipcMain.handle('workspace:revealInExplorer', async (event, relativePath: string) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const rel = String(relativePath ?? '');
    const abs = resolveAbs(root, rel);
    try {
      shell.showItemInFolder(abs);
      return { ok: true as const };
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg };
    }
  });

  ipcMain.handle('clipboard:writeText', async (_e, text: string) => {
    try {
      clipboard.writeText(String(text ?? ''));
      return { ok: true as const };
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg };
    }
  });

  ipcMain.handle('workspace:mkdir', async (event, params: { relativePath: string }) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const rel = String(params?.relativePath ?? '');
    const abs = resolveAbs(root, rel);
    try {
      await fs.promises.mkdir(abs, { recursive: true });
      return { ok: true as const };
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg };
    }
  });

  ipcMain.handle(
    'workspace:writeTextFile',
    async (event, params: { relativePath: string; content?: string; overwrite?: boolean }) => {
      const root = resolveWorkspaceRootForWebContents(event.sender);
      const rel = String(params?.relativePath ?? '');
      const abs = resolveAbs(root, rel);
      const content = String(params?.content ?? '');
      const overwrite = params?.overwrite !== false;
      try {
        await fs.promises.mkdir(path.dirname(abs), { recursive: true });
        const exists = await fs.promises
          .stat(abs)
          .then((s) => s.isFile() || s.isSymbolicLink())
          .catch(() => false);
        if (exists && !overwrite) return { ok: false as const, error: 'File exists (overwrite=false)' };
        await fs.promises.writeFile(abs, content, 'utf8');
        return { ok: true as const };
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : String(e);
        return { ok: false as const, error: msg };
      }
    }
  );

  ipcMain.handle('workspace:renamePath', async (event, params: { from: string; to: string; overwrite?: boolean }) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const fromRel = String(params?.from ?? '');
    const toRel = String(params?.to ?? '');
    const overwrite = params?.overwrite === true;
    const fromAbs = resolveAbs(root, fromRel);
    const toAbs = resolveAbs(root, toRel);
    try {
      await fs.promises.mkdir(path.dirname(toAbs), { recursive: true });
      const toExists = await fs.promises
        .stat(toAbs)
        .then(() => true)
        .catch(() => false);
      if (toExists && !overwrite) return { ok: false as const, error: 'Destination exists (overwrite=false)' };
      if (toExists && overwrite) await fs.promises.rm(toAbs, { recursive: true, force: true });
      await fs.promises.rename(fromAbs, toAbs);
      return { ok: true as const };
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg };
    }
  });

  ipcMain.handle('workspace:deletePath', async (event, params: { relativePath: string }) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const rel = String(params?.relativePath ?? '').trim();
    if (!rel) {
      return { ok: false as const, error: 'empty_path' };
    }
    let abs: string;
    try {
      abs = resolveAbs(root, rel);
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg };
    }
    try {
      await fs.promises.rm(abs, { recursive: true, force: true });
      return { ok: true as const };
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg };
    }
  });

  ipcMain.handle('workspace:getChangeLog', async (event, limit?: number) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const lim = typeof limit === 'number' && Number.isFinite(limit) ? limit : 100;
    const entries = await workspaceChangeLog.getWorkspaceChangeLog(root, lim);
    return { ok: true as const, entries };
  });

  ipcMain.handle(
    'workspace:appendChangeLog',
    async (event, payload: { conversationId: string; userPreview: string; assistantExcerpt: string }) => {
      const root = resolveWorkspaceRootForWebContents(event.sender);
      try {
        const entry = await workspaceChangeLog.appendWorkspaceChangeLog(root, {
          conversationId: String(payload?.conversationId ?? ''),
          userPreview: String(payload?.userPreview ?? ''),
          assistantExcerpt: String(payload?.assistantExcerpt ?? ''),
        });
        return { ok: true as const, entry };
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : String(e);
        return { ok: false as const, error: msg };
      }
    }
  );

  ipcMain.handle(
    'memoryFts:search',
    async (event, params: { query?: string; limit?: number; skillName?: string }) => {
      const root = resolveWorkspaceRootForWebContents(event.sender);
      const query = String(params?.query ?? '').trim();
      if (!query) return { ok: false as const, error: 'missing query' };
      const res = searchHermesMemory(root, {
        query,
        limit: params?.limit,
        skillName: params?.skillName != null ? String(params.skillName).trim() || undefined : undefined,
      });
      if (!res.ok) return { ok: false as const, error: res.error };
      return { ok: true as const, hits: res.hits };
    }
  );

  ipcMain.handle('memoryFts:rebuild', async (event) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const res = await rebuildHermesSkillFtsIndex(root);
    if (!res.ok) return { ok: false as const, error: res.error };
    return { ok: true as const, indexed: res.indexed, pruned: res.pruned };
  });

  ipcMain.handle('workspaceSkills:list', async (event) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    try {
      const disabled = readDisabledSkillRootsSync(root);
      const skills = listWorkspaceHermesSkills(root).map((s) => ({
        ...s,
        enabled: !disabled.has(s.skillRootRel.replace(/\\/g, '/')),
      }));
      return { ok: true as const, skills };
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg, skills: [] };
    }
  });

  ipcMain.handle('workspaceSkills:setEnabled', async (event, payload: unknown) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const o = payload && typeof payload === 'object' ? (payload as Record<string, unknown>) : {};
    const skillRootRel = typeof o.skillRootRel === 'string' ? o.skillRootRel.trim() : '';
    const enabled = o.enabled === true;
    if (!skillRootRel) return { ok: false as const, error: 'missing skillRootRel' };
    try {
      await setSkillRootEnabled(root, skillRootRel, enabled);
      return { ok: true as const };
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg };
    }
  });

  ipcMain.handle('workspaceSkills:deleteSkill', async (event, payload: unknown) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const o = payload && typeof payload === 'object' ? (payload as Record<string, unknown>) : {};
    const skillRootRel = typeof o.skillRootRel === 'string' ? o.skillRootRel.trim() : '';
    if (!skillRootRel) return { ok: false as const, error: 'missing skillRootRel' };
    const r = await deleteHermesSkillDirectory(root, skillRootRel);
    if (!r.ok) return { ok: false as const, error: r.error };
    try {
      await setSkillRootEnabled(root, skillRootRel, true);
    } catch {
      /* ignore */
    }
    return { ok: true as const };
  });

  ipcMain.handle('workspaceSkills:readFile', async (event, relativePath: string) => {
    const root = resolveWorkspaceRootForWebContents(event.sender);
    const rel = String(relativePath ?? '').trim();
    if (!rel) return { ok: false as const, error: 'missing path' };
    const r = readWorkspaceSkillTextFile(root, rel);
    if (!r.ok) return { ok: false as const, error: r.error };
    return { ok: true as const, content: r.content };
  });
}

let windowControlIpcRegistered = false;

function registerWindowControlIpcOnce(): void {
  if (windowControlIpcRegistered) return;
  windowControlIpcRegistered = true;
  ipcMain.handle('window:minimize', (event) => BrowserWindow.fromWebContents(event.sender)?.minimize());
  ipcMain.handle('window:toggleMaximize', (event) => {
    const win = BrowserWindow.fromWebContents(event.sender);
    if (!win) return;
    if (win.isMaximized()) win.unmaximize();
    else win.maximize();
  });
  ipcMain.handle('window:close', (event) => BrowserWindow.fromWebContents(event.sender)?.close());
  ipcMain.handle('window:reload', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.reload());
  ipcMain.handle('window:toggleDevTools', (event) => {
    const wc = BrowserWindow.fromWebContents(event.sender)?.webContents;
    if (!wc) return;
    if (wc.isDevToolsOpened()) wc.closeDevTools();
    else wc.openDevTools({ mode: 'detach' });
  });
  ipcMain.handle('window:undo', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.undo());
  ipcMain.handle('window:redo', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.redo());
  ipcMain.handle('window:cut', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.cut());
  ipcMain.handle('window:copy', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.copy());
  ipcMain.handle('window:paste', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.paste());
  ipcMain.handle('window:selectAll', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.selectAll());
  ipcMain.handle('app:quit', () => app.quit());
  ipcMain.handle('app:relaunch', () => {
    app.relaunch();
    app.exit(0);
  });
}

function buildBaseBrowserWindow(): BrowserWindow {
  const win = new BrowserWindow({
    height: 800,
    width: 1200,
    // Windows：无边框窗口，由页面内 Titlebar / 便签顶栏提供拖动与窗口按钮（无系统标题栏条）
    // Windows：透明 + 无边框时若保留 roundedCorners，DWM 常无法把桌面合成进来（表现为发灰/不透）。
    // 便签玻璃依赖 OS 级透明，故关闭系统圆角；界面圆角由页面 CSS 承担。
    ...(process.platform === 'win32'
      ? {
          frame: false,
          roundedCorners: false,
          transparent: true,
          backgroundColor: '#00000000',
        }
      : {}),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
      webviewTag: true,
    },
  });

  if (!app.isPackaged) {
    win.webContents.on('before-input-event', (event, input) => {
      if (input.type !== 'keyDown') return;
      if (input.code !== 'F12' || !input.control || input.meta || input.alt) return;
      event.preventDefault();
      const wc = win.webContents;
      if (wc.isDevToolsOpened()) wc.closeDevTools();
      else wc.openDevTools({ mode: 'detach' });
    });
  }

  if (process.platform === 'win32') {
    try {
      win.setBackgroundColor('#00000000');
    } catch {
      /* ignore */
    }
  }

  if (process.platform === 'win32') {
    win.setMenuBarVisibility(false);
    win.removeMenu();
    win.setAutoHideMenuBar(true);
  }

  win.on('focus', () => applyWorkspaceForFocusedWindow(win));
  return win;
}

function registerStickySatelliteIPC(): void {
  const rm = (channel: string) => {
    try {
      ipcMain.removeHandler(channel);
    } catch {
      /* first load */
    }
  };
  rm('sticky:getBootstrap');
  rm('sticky:getDetachedPaths');
  rm('sticky:openSatellite');
  rm('sticky:mergeSatellite');

  ipcMain.handle('sticky:getBootstrap', (event) => {
    const win = BrowserWindow.fromWebContents(event.sender);
    if (!win) return { role: 'main' as const, satelliteWorkspace: null as string | null };
    const p = stickySatellitePathByWindowId.get(win.id) ?? null;
    return { role: p ? ('satellite' as const) : ('main' as const), satelliteWorkspace: p };
  });

  ipcMain.handle('sticky:getDetachedPaths', () => ({
    paths: [...new Set(stickySatellitePathByWindowId.values())],
  }));

  ipcMain.handle('sticky:openSatellite', async (_event, params: { workspacePath?: string }) => {
    const raw = String(params?.workspacePath ?? '').trim();
    if (!raw) return { ok: false as const, error: 'missing_path' };
    const resolved = path.resolve(raw);
    const def = workspaceService.getDefaultWorkspacePath();
    if (workspaceService.isSameWorkspacePath(resolved, def)) {
      return { ok: false as const, error: 'cannot_detach_default' };
    }
    for (const w of BrowserWindow.getAllWindows()) {
      if (w.isDestroyed()) continue;
      const p = stickySatellitePathByWindowId.get(w.id);
      if (p && workspaceService.isSameWorkspacePath(p, resolved)) {
        bumpMainShellWorkspaceIfSameAsSatelliteBinding(resolved);
        w.focus();
        return { ok: true as const, focused: true as const };
      }
    }
    registerWindowControlIpcOnce();
    const win = buildBaseBrowserWindow();
    stickySatellitePathByWindowId.set(win.id, resolved);
    win.on('closed', () => {
      stickySatellitePathByWindowId.delete(win.id);
      broadcastStickyDetachedPaths();
    });
    win.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
    win.once('ready-to-show', () => {
      try {
        win.show();
        win.focus();
      } catch {
        /* ignore */
      }
    });
    broadcastStickyDetachedPaths();
    bumpMainShellWorkspaceIfSameAsSatelliteBinding(resolved);
    return { ok: true as const, focused: false as const };
  });

  ipcMain.handle('sticky:mergeSatellite', async (_event, params: { workspacePath?: string }) => {
    const raw = String(params?.workspacePath ?? '').trim();
    if (!raw) return { ok: false as const, error: 'missing_path' };
    const resolved = path.resolve(raw);
    const hit = [...stickySatellitePathByWindowId.entries()].find(([, p]) =>
      workspaceService.isSameWorkspacePath(p, resolved)
    );
    if (!hit) return { ok: true as const, closed: false as const };
    const [winId] = hit;
    const win = BrowserWindow.getAllWindows().find((w) => w.id === winId && !w.isDestroyed());
    win?.close();
    return { ok: true as const, closed: true as const };
  });
}

registerStickySatelliteIPC();

const createWindow = (): void => {
  registerWindowControlIpcOnce();
  const mainWindow = buildBaseBrowserWindow();
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(async () => {
  const reg = workspaceService.loadRegistry();
  // 如果刚执行了“取消置顶 active”的一次性迁移，这里需要写回磁盘
  if (!reg.unpinActiveMigrated && reg.activeWorkspacePath) {
    workspaceService.saveRegistry({ ...reg, unpinActiveMigrated: true });
  }
  const active = reg.activeWorkspacePath ?? workspaceService.getDefaultWorkspacePath();
  workspaceService.migrateWorkspaceOpenclawToGlobalOnce();
  workspaceService.removeLegacyWorkspaceOpenclawDirs();
  await workspaceService.ensureWorkspaceInitialized(active);
  workspaceService.setActiveWorkspace(active);
  setActiveWorkspaceRoot(active);
  setMainShellLastWorkspacePath(active);

  registerWorkspaceIPC();
  try {
    rescheduleAllTodoTriggers();
  } catch (e: unknown) {
    console.warn('[todoTriggers] initial schedule failed:', e instanceof Error ? e.message : e);
  }
  registerOpenClawIPC();
  const webSearchProvider = String(process.env.CLAWFLOW_WEB_SEARCH_PROVIDER ?? 'auto').toLowerCase();
  registerClawFlowIPC({
    workspaceRoot: active,
    verbose: true,
    webSearch: {
      enabled: process.env.CLAWFLOW_WEB_SEARCH_DISABLED === '1' ? false : undefined,
      provider:
        webSearchProvider === 'brave' || webSearchProvider === 'duckduckgo'
          ? webSearchProvider
          : 'auto',
      braveApiKey: process.env.BRAVE_API_KEY,
    },
  });
  registerGatewayIPC();
  // Phase 3: keep internal GatewayDaemon resident (best-effort)
  try {
    await getGatewayDaemon().start();
  } catch (e: any) {
    console.warn('[GatewayDaemon] auto-start failed:', e?.message ?? e);
  }
  ipcMain.handle('app:getVersion', () => app.getVersion());
  ipcMain.handle('app:setLanguage', (_event, lang: string) => {
    currentLang = String(lang).toLowerCase().startsWith('en') ? 'en' : 'zh';
    setupApplicationMenu();
    return { success: true };
  });
  setupApplicationMenu();

  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
