/**
 * Electron 主进程入口（Webpack `main` entry）。
 * 职责与阅读顺序见仓库根目录 `AGENTS.md`；应用菜单与语言见 `src/main/application-menu.ts`。
 */
import './main/win-console-utf8';
import { app, BrowserWindow, ipcMain, shell, clipboard, screen } from 'electron';
import * as path from 'path';
import * as fs from 'fs';
import { getActiveWorkspaceRoot } from './engine/active-workspace-root';
import { syncClawFlowEngineWorkspaceRoot } from './engine/clawflow-engine';
import { registerClawFlowIPC } from './engine/engine-ipc';
import {
  applyActiveWorkspace,
  clearActiveWorkspaceRootInMemory,
  syncActiveWorkspaceRootToEngine,
} from './main/workspace/active-workspace-sync';
import { registerScrapeIPC, registerTodoTriggersIPC } from './main/ipc/register-todo-scrape-ipc';
import { registerWorkspaceIPC } from './main/ipc/workspace-ipc';
import { getGatewayDaemon, registerGatewayIPC } from './engine/gateway-daemon';
import { sanitizeAppCachePrefsOnStartupSync } from './main/prefs/app-cache-prefs';
import * as workspaceService from './main/workspace/workspace-service';
import {
  migrateLegacyTriadForWorkspaceRootsSync,
  mergeLegacyWorkspacesTreesIntoEffectiveSync,
  setAppCacheRootAndMigrate,
} from './main/workspace/workspace-blob-store';
import { getDefaultAppCacheRootSync, getEffectiveAppCacheRootSync, readAppCachePrefsFile } from './main/prefs/app-cache-prefs';
import * as workspaceExplorer from './main/workspace/workspace-explorer';
import { broadcastWorkspaceFilesUpdated } from './main/workspace/workspace-files-broadcast';
import {
  requireWorkspaceRootForWebContents,
  resolveWorkspaceRootForWebContents,
} from './main/electron-workspace-context';
import { stickySatellitePathByWindowId } from './main/sticky-satellite-windows';
import { getMainShellLastWorkspacePath, setMainShellLastWorkspacePath } from './main/shell/main-shell-workspace';
import { registerSystemAgentsIPC } from './main/system-agents/system-agents-ipc';
import { rescheduleAllTodoTriggers } from './main/todo/todo-triggers-scheduler';
import { getLauncherIconDataUrl } from './main/shell/launcher-icon-main';
import { readMainUiPrefsFromDisk, saveMainUiPrefs, getMainUiPrefs } from './main/shell/main-ui-prefs';
import { destroyAppTray, ensureAppTray } from './main/shell/app-tray';
import { registerMessagingIPC } from './messaging/register-messaging-ipc';
import { stopFeishuEventServer, restartFeishuEventServerFromPrefs } from './messaging/feishu-event-server';
import { getAppLanguage, setAppLanguageFromRenderer, setupApplicationMenu } from './main/application-menu';
import { registerDesktopPinSessionRestoreOnQuit, setDesktopEntryHidden, sweepLauncherStashForWorkspace } from './main/shell/desktop-pin-hide-main';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).

declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// 须在主进程启动时即注册，避免仅放在 app.whenReady 链后部时因前置步骤异常而未注册，导致渲染层报 “No handler registered”。
registerMessagingIPC();

/** 便签紧凑窗口：按 BrowserWindow 分别保存 bounds，支持多窗口 */
type ShellCompactState = { restoreBounds: Electron.Rectangle; restoreMaximized: boolean };
const shellCompactByWindowId = new Map<number, ShellCompactState>();

function broadcastStickyDetachedPaths(): void {
  const paths = [...new Set(stickySatellitePathByWindowId.values())];
  BrowserWindow.getAllWindows().forEach((w) => {
    if (!w.isDestroyed()) w.webContents.send('sticky:detachedPaths', { paths });
  });
  try {
    rescheduleAllTodoTriggers();
  } catch {
    /* ignore */
  }
}

/** 主壳若仍指向刚拖出到卫星的工作区，则改记到下一个可用路径并通知各窗刷新（避免主窗 UI/IPC 仍停在已分离工作区） */
function bumpMainShellWorkspaceIfSameAsSatelliteBinding(detachedResolved: string): void {
  const last = getMainShellLastWorkspacePath();
  if (!last || !workspaceService.isSameWorkspacePath(last, detachedResolved)) return;

  const reg = workspaceService.loadRegistry();
  const recent = reg.recentWorkspacePaths ?? [];
  let next: string | null = null;
  for (const p of recent) {
    if (!workspaceService.isSameWorkspacePath(p, detachedResolved)) {
      next = path.resolve(p);
      break;
    }
  }
  setMainShellLastWorkspacePath(next);
  BrowserWindow.getAllWindows().forEach((w) => {
    if (!w.isDestroyed()) w.webContents.send('workspace:changed', { path: next });
  });
}

function applyWorkspaceForFocusedWindow(win: BrowserWindow | null): void {
  if (!win || win.isDestroyed()) return;
  const sat = stickySatellitePathByWindowId.get(win.id);
  const target = sat ?? getMainShellLastWorkspacePath();
  if (!target) return;
  const cur = getActiveWorkspaceRoot();
  if (cur && workspaceService.isSameWorkspacePath(cur, target)) return;
  applyActiveWorkspace(target);
  BrowserWindow.getAllWindows().forEach((w) => {
    if (!w.isDestroyed()) w.webContents.send('workspace:changed', { path: target });
  });
}

function registerShellViewWindowIPC(): void {
  try {
    ipcMain.removeHandler('window:setShellViewAppearance');
  } catch {
    /* first load or older Electron */
  }
  ipcMain.handle('window:setShellViewAppearance', (_event, params: { compact?: boolean }) => {
    const win = BrowserWindow.fromWebContents(_event.sender);
    if (!win || win.isDestroyed()) return { ok: false as const, error: 'no_window' };
    const wantCompact = Boolean(params?.compact);

    if (wantCompact) {
      if (!shellCompactByWindowId.has(win.id)) {
        const restoreMaximized = win.isMaximized();
        if (restoreMaximized) win.unmaximize();
        const restoreBounds = win.getBounds();
        shellCompactByWindowId.set(win.id, { restoreBounds, restoreMaximized });
      }
      const wa = screen.getDisplayMatching(win.getBounds()).workArea;
      /** 便签：宽约工作区 32%（下限 380px），便于文件列表横向展示；高度贴右侧竖条 */
      const width = Math.max(380, Math.floor(wa.width * 0.32));
      const marginTop = 10;
      const marginBottom = 18;
      const height = Math.max(420, wa.height - marginTop - marginBottom);
      const x = wa.x + wa.width - width;
      const y = wa.y + marginTop;
      win.setMinimumSize(300, 320);
      win.setBounds({ x, y, width, height }, true);
      return { ok: true as const };
    }

    const st = shellCompactByWindowId.get(win.id);
    if (st) {
      shellCompactByWindowId.delete(win.id);
      try {
        win.setMinimumSize(0, 0);
      } catch {
        /* ignore */
      }
      win.setBounds(st.restoreBounds, true);
      if (st.restoreMaximized) win.maximize();
    }
    return { ok: true as const };
  });
}

/** 主进程一加载即注册，避免 whenReady 内前置 await 未完成时渲染进程已发起 invoke */
registerShellViewWindowIPC();

/** 外部拖入文件：须与 preload 同步，在模块加载时注册，避免 invoke 早于 registerWorkspaceIPC */
function registerWorkspaceImportExternalPathsIPC(): void {
  try {
    ipcMain.removeHandler('workspace:importExternalPaths');
  } catch {
    /* first load */
  }
  ipcMain.handle(
    'workspace:importExternalPaths',
    async (
      event,
      params: { targetRelativeDir: string; sourceAbsolutePaths: string[]; overwrite?: boolean }
    ) => {
      const root = requireWorkspaceRootForWebContents(event.sender);
      try {
        const result = await workspaceExplorer.importExternalPathsIntoWorkspace(
          root,
          String(params?.targetRelativeDir ?? ''),
          Array.isArray(params?.sourceAbsolutePaths) ? params.sourceAbsolutePaths : [],
          { overwrite: params?.overwrite !== false }
        );
        if (result.ok) broadcastWorkspaceFilesUpdated(root);
        return result;
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : String(e);
        return { ok: false as const, error: msg };
      }
    }
  );
}
registerWorkspaceImportExternalPathsIPC();

function registerWorkspaceCopyChatDropFilesIPC(): void {
  try {
    ipcMain.removeHandler('workspace:copyChatDropFiles');
  } catch {
    /* first load */
  }
  ipcMain.handle('workspace:copyChatDropFiles', async (event, params: { sourceAbsolutePaths: string[] }) => {
    const root = requireWorkspaceRootForWebContents(event.sender);
    try {
      return await workspaceExplorer.copyExternalPathsToChatDropCache(
        root,
        Array.isArray(params?.sourceAbsolutePaths) ? params.sourceAbsolutePaths : []
      );
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg };
    }
  });
}
registerWorkspaceCopyChatDropFilesIPC();

/** 便签拖入文件夹：须在 whenReady 前可用，避免渲染进程早于 registerWorkspaceIPC 发起 invoke */
function registerWorkspaceStatAbsolutePathIPC(): void {
  try {
    ipcMain.removeHandler('workspace:statAbsolutePath');
  } catch {
    /* first load */
  }
  ipcMain.handle('workspace:statAbsolutePath', async (_e, absPath: string) => {
    const resolved = path.resolve(String(absPath || ''));
    try {
      const st = await fs.promises.stat(resolved);
      return { ok: true as const, path: resolved, isDirectory: st.isDirectory() };
    } catch {
      return { ok: false as const, error: 'not_found' as const };
    }
  });
}
registerWorkspaceStatAbsolutePathIPC();

/** 打开绝对路径 / 读取系统文件图标：模块加载时注册，避免 whenReady 前序 await 导致 invoke 无 handler */
function registerAppPathAndIconIPC(): void {
  for (const ch of ['app:openPath', 'app:getFileIconDataUrl', 'app:setPathHidden', 'app:sweepLauncherStash'] as const) {
    try {
      ipcMain.removeHandler(ch);
    } catch {
      /* first load */
    }
  }

  ipcMain.handle('app:openPath', async (_e, absolutePath: string) => {
    const raw = String(absolutePath ?? '').trim();
    if (!raw || !path.isAbsolute(raw)) {
      return { ok: false as const, error: 'invalid_path' };
    }
    try {
      const st = await fs.promises.stat(raw);
      if (st.isFile() || st.isSymbolicLink()) {
        /* ok */
      } else if (st.isDirectory() && raw.toLowerCase().endsWith('.app')) {
        /* macOS .app bundle */
      } else {
        return { ok: false as const, error: 'unsupported' };
      }
    } catch {
      return { ok: false as const, error: 'not_found' };
    }
    try {
      const err = await shell.openPath(raw);
      if (err) return { ok: false as const, error: err };
      return { ok: true as const };
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg };
    }
  });

  ipcMain.handle('app:getFileIconDataUrl', async (_e, absolutePath: string) => getLauncherIconDataUrl(absolutePath));

  ipcMain.handle(
    'app:setPathHidden',
    async (
      _e,
      payload: { absolutePath?: string; hidden?: boolean; workspacePath?: string }
    ) => {
      const abs = String(payload?.absolutePath ?? '').trim();
      const hidden = Boolean(payload?.hidden);
      const ws = String(payload?.workspacePath ?? '').trim();
      return setDesktopEntryHidden(abs, hidden, ws || undefined);
    }
  );

  ipcMain.handle('app:sweepLauncherStash', async (_e, payload: { workspacePath?: string }) => {
    const ws = String(payload?.workspacePath ?? '').trim();
    if (!ws) return { ok: false as const, error: 'workspace_required' as const };
    await sweepLauncherStashForWorkspace(ws);
    return { ok: true as const };
  });
}
registerAppPathAndIconIPC();
registerDesktopPinSessionRestoreOnQuit();

registerTodoTriggersIPC();
registerSystemAgentsIPC();
registerScrapeIPC();

let windowControlIpcRegistered = false;

function registerWindowControlIpcOnce(): void {
  if (windowControlIpcRegistered) return;
  windowControlIpcRegistered = true;
  ipcMain.handle('window:minimize', (event) => BrowserWindow.fromWebContents(event.sender)?.minimize());
  ipcMain.handle('window:toggleMaximize', (event) => {
    const win = BrowserWindow.fromWebContents(event.sender);
    if (!win) return;
    if (win.isMaximized()) win.unmaximize();
    else win.maximize();
  });
  ipcMain.handle('window:close', (event) => {
    const win = BrowserWindow.fromWebContents(event.sender);
    if (!win || win.isDestroyed()) return;
    const prefs = getMainUiPrefs();
    if (prefs.closeButtonAction === 'minimizeToTray') {
      win.hide();
      if (process.platform === 'win32' || process.platform === 'linux') {
        try {
          ensureAppTray(
            () => getAppLanguage(),
            () => {
              destroyAppTray();
              app.quit();
            }
          );
        } catch (e) {
          console.warn('[app-tray] ensure failed:', e);
        }
      }
      return;
    }
    win.close();
  });
  ipcMain.handle('window:reload', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.reload());
  ipcMain.handle('window:toggleDevTools', (event) => {
    const wc = BrowserWindow.fromWebContents(event.sender)?.webContents;
    if (!wc) return;
    if (wc.isDevToolsOpened()) wc.closeDevTools();
    else wc.openDevTools({ mode: 'detach' });
  });
  ipcMain.handle('window:undo', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.undo());
  ipcMain.handle('window:redo', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.redo());
  ipcMain.handle('window:cut', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.cut());
  ipcMain.handle('window:copy', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.copy());
  ipcMain.handle('window:paste', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.paste());
  ipcMain.handle('window:selectAll', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.selectAll());
  ipcMain.handle('app:syncMainUiPrefs', (_e, payload: unknown) => {
    const o = payload && typeof payload === 'object' ? (payload as Record<string, unknown>) : {};
    const a = o.closeButtonAction === 'minimizeToTray' ? 'minimizeToTray' : 'quit';
    saveMainUiPrefs({ closeButtonAction: a });
    return { ok: true as const };
  });
  ipcMain.handle('app:quit', () => app.quit());
  ipcMain.handle('app:relaunch', () => {
    app.relaunch();
    app.exit(0);
  });
}

function buildBaseBrowserWindow(): BrowserWindow {
  const win = new BrowserWindow({
    height: 800,
    width: 1200,
    /** 显式开启，避免部分平台/版本在无边框组合下误判为不可缩放 */
    resizable: true,
    movable: true,
    minimizable: true,
    maximizable: true,
    // Windows：无边框窗口，由页面内 Titlebar / 便签顶栏提供拖动与窗口按钮（无系统标题栏条）
    // Windows：透明 + 无边框时若保留 roundedCorners，DWM 常无法把桌面合成进来（表现为发灰/不透）。
    // 便签玻璃依赖 OS 级透明，故关闭系统圆角；界面圆角由页面 CSS 承担。
    // thickFrame：参与 Win32 边缘缩放（WS_THICKFRAME）；透明无边框曾出现边缘不可缩放回归（electron#48554），需较新 Chromium/Electron。
    ...(process.platform === 'win32'
      ? {
          frame: false,
          roundedCorners: false,
          transparent: true,
          backgroundColor: '#00000000',
          thickFrame: true,
        }
      : {}),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
      webviewTag: true,
    },
  });

  if (!app.isPackaged) {
    win.webContents.on('before-input-event', (event, input) => {
      if (input.type !== 'keyDown') return;
      if (input.code !== 'F12' || !input.control || input.meta || input.alt) return;
      event.preventDefault();
      const wc = win.webContents;
      if (wc.isDevToolsOpened()) wc.closeDevTools();
      else wc.openDevTools({ mode: 'detach' });
    });
  }

  if (process.platform === 'win32') {
    try {
      win.setResizable(true);
    } catch {
      /* ignore */
    }
    try {
      win.setBackgroundColor('#00000000');
    } catch {
      /* ignore */
    }
  }

  if (process.platform === 'win32') {
    win.setMenuBarVisibility(false);
    win.removeMenu();
    win.setAutoHideMenuBar(true);
  }

  win.on('focus', () => applyWorkspaceForFocusedWindow(win));
  return win;
}

function registerStickySatelliteIPC(): void {
  const rm = (channel: string) => {
    try {
      ipcMain.removeHandler(channel);
    } catch {
      /* first load */
    }
  };
  rm('sticky:getBootstrap');
  rm('sticky:getDetachedPaths');
  rm('sticky:openSatellite');
  rm('sticky:mergeSatellite');

  ipcMain.handle('sticky:getBootstrap', (event) => {
    const win = BrowserWindow.fromWebContents(event.sender);
    if (!win) return { role: 'main' as const, satelliteWorkspace: null as string | null };
    const p = stickySatellitePathByWindowId.get(win.id) ?? null;
    return { role: p ? ('satellite' as const) : ('main' as const), satelliteWorkspace: p };
  });

  ipcMain.handle('sticky:getDetachedPaths', () => ({
    paths: [...new Set(stickySatellitePathByWindowId.values())],
  }));

  ipcMain.handle('sticky:openSatellite', async (_event, params: { workspacePath?: string }) => {
    const raw = String(params?.workspacePath ?? '').trim();
    if (!raw) return { ok: false as const, error: 'missing_path' };
    const resolved = path.resolve(raw);
    for (const w of BrowserWindow.getAllWindows()) {
      if (w.isDestroyed()) continue;
      const p = stickySatellitePathByWindowId.get(w.id);
      if (p && workspaceService.isSameWorkspacePath(p, resolved)) {
        bumpMainShellWorkspaceIfSameAsSatelliteBinding(resolved);
        w.focus();
        return { ok: true as const, focused: true as const };
      }
    }
    registerWindowControlIpcOnce();
    const win = buildBaseBrowserWindow();
    stickySatellitePathByWindowId.set(win.id, resolved);
    win.on('closed', () => {
      stickySatellitePathByWindowId.delete(win.id);
      broadcastStickyDetachedPaths();
    });
    win.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
    win.once('ready-to-show', () => {
      try {
        win.show();
        win.focus();
      } catch {
        /* ignore */
      }
    });
    broadcastStickyDetachedPaths();
    bumpMainShellWorkspaceIfSameAsSatelliteBinding(resolved);
    return { ok: true as const, focused: false as const };
  });

  ipcMain.handle('sticky:mergeSatellite', async (_event, params: { workspacePath?: string }) => {
    const raw = String(params?.workspacePath ?? '').trim();
    if (!raw) return { ok: false as const, error: 'missing_path' };
    const resolved = path.resolve(raw);
    const hit = [...stickySatellitePathByWindowId.entries()].find(([, p]) =>
      workspaceService.isSameWorkspacePath(p, resolved)
    );
    if (!hit) return { ok: true as const, closed: false as const };
    const [winId] = hit;
    const win = BrowserWindow.getAllWindows().find((w) => w.id === winId && !w.isDestroyed());
    win?.close();
    return { ok: true as const, closed: true as const };
  });
}

registerStickySatelliteIPC();

const createWindow = (): void => {
  registerWindowControlIpcOnce();
  const mainWindow = buildBaseBrowserWindow();
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(async () => {
  readMainUiPrefsFromDisk();
  sanitizeAppCachePrefsOnStartupSync();
  workspaceService.migrateLegacyWorkspaceRegistryIfEmptySync();
  mergeLegacyWorkspacesTreesIntoEffectiveSync();
  const reg = workspaceService.loadRegistry();
  const rootsForTriad = new Set<string>();
  for (const p of reg.recentWorkspacePaths ?? []) {
    const r = path.resolve(String(p ?? '').trim());
    if (r) rootsForTriad.add(r);
  }
  if (reg.activeWorkspacePath) {
    const r = path.resolve(String(reg.activeWorkspacePath).trim());
    if (r) rootsForTriad.add(r);
  }
  migrateLegacyTriadForWorkspaceRootsSync([...rootsForTriad]);
  // 如果刚执行了“取消置顶 active”的一次性迁移，这里需要写回磁盘
  if (!reg.unpinActiveMigrated && reg.activeWorkspacePath) {
    workspaceService.saveRegistry({ ...reg, unpinActiveMigrated: true });
  }
  const activeRaw = reg.activeWorkspacePath?.trim() ? path.resolve(reg.activeWorkspacePath.trim()) : null;
  workspaceService.removeLegacyExternalAgentStateDirsSync();
  if (activeRaw) {
    await workspaceService.ensureWorkspaceInitialized(activeRaw);
  }
  try {
    const { ensureSystemAgentsInitialized } = await import('./main/system-agents/system-agent-roster-bootstrap');
    const tools = activeRaw ? await workspaceService.readWorkspaceToolManifest(activeRaw) : null;
    await ensureSystemAgentsInitialized(Boolean(tools?.skills));
  } catch (e: unknown) {
    console.warn('[system-agents] init failed:', e instanceof Error ? e.message : e);
  }
  if (activeRaw) {
    workspaceService.setActiveWorkspace(activeRaw);
    syncActiveWorkspaceRootToEngine(activeRaw);
    setMainShellLastWorkspacePath(activeRaw);
  } else {
    clearActiveWorkspaceRootInMemory();
  }

  registerWorkspaceIPC();
  try {
    rescheduleAllTodoTriggers();
  } catch (e: unknown) {
    console.warn('[todoTriggers] initial schedule failed:', e instanceof Error ? e.message : e);
  }
  const webSearchProvider = String(process.env.CLAWFLOW_WEB_SEARCH_PROVIDER ?? 'searxng').toLowerCase();
  registerClawFlowIPC({
    workspaceRoot: activeRaw ?? undefined,
    verbose: false,
    webSearch: {
      enabled: process.env.CLAWFLOW_WEB_SEARCH_DISABLED === '1' ? false : undefined,
      provider:
        webSearchProvider === 'brave' ||
        webSearchProvider === 'duckduckgo' ||
        webSearchProvider === 'searxng' ||
        webSearchProvider === 'bocha'
          ? webSearchProvider
          : 'auto',
      braveApiKey: process.env.BRAVE_API_KEY,
      braveBaseUrl: process.env.BRAVE_BASE_URL,
      bochaApiKey: process.env.BOCHA_API_KEY,
      bochaBaseUrl: process.env.BOCHA_BASE_URL,
      searxngBaseUrl: process.env.CLAWFLOW_SEARXNG_URL,
      searxngApiKey: process.env.CLAWFLOW_SEARXNG_API_KEY,
    },
  });
  registerGatewayIPC();
  // Phase 3: keep internal GatewayDaemon resident (best-effort)
  try {
    await getGatewayDaemon().start();
  } catch (e: any) {
    console.warn('[GatewayDaemon] auto-start failed:', e?.message ?? e);
  }
  ipcMain.handle('app:getVersion', () => app.getVersion());
  ipcMain.handle('app:getAppCacheSettings', () => {
    const prefs = readAppCachePrefsFile();
    const configured =
      typeof prefs.cacheRoot === 'string' && prefs.cacheRoot.trim() ? prefs.cacheRoot.trim() : null;
    return {
      effectiveRoot: getEffectiveAppCacheRootSync(),
      defaultRoot: getDefaultAppCacheRootSync(),
      configuredRoot: configured,
    };
  });
  ipcMain.handle('app:setAppCacheRoot', async (_e, folderPath: string | null | undefined) =>
    setAppCacheRootAndMigrate(folderPath ?? null)
  );
  ipcMain.handle('app:setLanguage', (_event, lang: string) => {
    setAppLanguageFromRenderer(lang);
    return { success: true };
  });
  setupApplicationMenu();

  createWindow();
  restartFeishuEventServerFromPrefs();
});

app.on('before-quit', () => {
  stopFeishuEventServer();
  destroyAppTray();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform === 'darwin') return;
  if (getMainUiPrefs().closeButtonAction === 'minimizeToTray') {
    return;
  }
  app.quit();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
