import { app, BrowserWindow, Menu, ipcMain } from 'electron';
import * as path from 'path';
import {
  registerOpenClawIPC,
  setActiveWorkspaceRoot,
  getActiveWorkspaceRoot,
  getGlobalOpenClawCliEngine,
} from './engine/openclaw-engine';
import { registerClawFlowIPC, syncClawFlowEngineWorkspaceRoot } from './engine/clawflow-engine';
import { getGatewayDaemon, registerGatewayIPC } from './engine/gateway-daemon';
import * as workspaceService from './workspace-service';
import * as workspaceExplorer from './workspace-explorer';
import * as workspaceChangeLog from './workspace-change-log';
import { fetchSkillMarketIndex } from './skill-market-service';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

type AppLang = 'zh' | 'en';
let currentLang: AppLang = app.getLocale().toLowerCase().startsWith('zh') ? 'zh' : 'en';

const I18N: Record<AppLang, Record<string, string>> = {
  zh: {
    file: '文件',
    edit: '编辑',
    view: '视图',
    window: '窗口',
    help: '帮助',
    about: '关于',
    services: '服务',
    hide: '隐藏',
    hideOthers: '隐藏其他',
    unhide: '显示全部',
    quit: '退出',
    undo: '撤销',
    redo: '重做',
    cut: '剪切',
    copy: '复制',
    paste: '粘贴',
    pasteAndMatchStyle: '粘贴并匹配样式',
    delete: '删除',
    selectAll: '全选',
    speech: '朗读',
    reload: '重新加载',
    forceReload: '强制重新加载',
    toggleDevTools: '切换开发者工具',
    resetZoom: '重置缩放',
    zoomIn: '放大',
    zoomOut: '缩小',
    togglefullscreen: '切换全屏',
    minimize: '最小化',
    zoom: '缩放',
    close: '关闭',
    front: '全部置于前台',
    learnMore: '了解更多',
    navChat: '对话',
    navSkills: '技能',
    navConnectors: '连接器',
    navSettings: '全局设置',
  },
  en: {
    file: 'File',
    edit: 'Edit',
    view: 'View',
    window: 'Window',
    help: 'Help',
    about: 'About',
    services: 'Services',
    hide: 'Hide',
    hideOthers: 'Hide Others',
    unhide: 'Show All',
    quit: 'Quit',
    undo: 'Undo',
    redo: 'Redo',
    cut: 'Cut',
    copy: 'Copy',
    paste: 'Paste',
    pasteAndMatchStyle: 'Paste and Match Style',
    delete: 'Delete',
    selectAll: 'Select All',
    speech: 'Speech',
    reload: 'Reload',
    forceReload: 'Force Reload',
    toggleDevTools: 'Toggle DevTools',
    resetZoom: 'Reset Zoom',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    togglefullscreen: 'Toggle Full Screen',
    minimize: 'Minimize',
    zoom: 'Zoom',
    close: 'Close',
    front: 'Bring All to Front',
    learnMore: 'Learn More',
    navChat: 'Chat',
    navSkills: 'Skills',
    navConnectors: 'Connectors',
    navSettings: 'Global settings',
  },
};

const setupApplicationMenu = () => {
  const isMac = process.platform === 'darwin';
  const nav = (path: string) => {
    const win = BrowserWindow.getAllWindows()[0];
    if (!win) return;
    win.webContents.send('app:navigate', path);
  };
  const t = (k: string) => I18N[currentLang][k] ?? k;

  const template: Electron.MenuItemConstructorOptions[] = [
    ...(isMac
      ? ([
          {
            label: app.name,
            submenu: [
              { role: 'about', label: `${t('about')} ${app.name}` },
              { type: 'separator' },
              { role: 'services', label: t('services') },
              { type: 'separator' },
              { role: 'hide', label: `${t('hide')} ${app.name}` },
              { role: 'hideOthers', label: t('hideOthers') },
              { role: 'unhide', label: t('unhide') },
              { type: 'separator' },
              { role: 'quit', label: `${t('quit')} ${app.name}` },
            ],
          },
        ] as Electron.MenuItemConstructorOptions[])
      : []),
    {
      label: t('file'),
      submenu: [
        ...(isMac
          ? ([] as Electron.MenuItemConstructorOptions[])
          : ([
              { role: 'quit', label: t('quit') },
            ] as Electron.MenuItemConstructorOptions[])),
      ],
    },
    {
      label: t('edit'),
      submenu: [
        { role: 'undo', label: t('undo') },
        { role: 'redo', label: t('redo') },
        { type: 'separator' },
        { role: 'cut', label: t('cut') },
        { role: 'copy', label: t('copy') },
        { role: 'paste', label: t('paste') },
        ...(isMac
          ? ([
              { role: 'pasteAndMatchStyle', label: t('pasteAndMatchStyle') },
              { role: 'delete', label: t('delete') },
              { role: 'selectAll', label: t('selectAll') },
              { type: 'separator' },
              { role: 'speech', label: t('speech') },
            ] as Electron.MenuItemConstructorOptions[])
          : ([
              { role: 'delete', label: t('delete') },
              { type: 'separator' },
              { role: 'selectAll', label: t('selectAll') },
            ] as Electron.MenuItemConstructorOptions[])),
      ],
    },
    {
      label: t('view'),
      submenu: [
        { label: t('navChat'), click: () => nav('/chat') },
        { label: t('navSkills'), click: () => nav('/skills') },
        { label: t('navConnectors'), click: () => nav('/connectors') },
        { label: t('navSettings'), click: () => nav('/settings') },
        { type: 'separator' },
        { role: 'reload', label: t('reload') },
        { role: 'forceReload', label: t('forceReload') },
        { role: 'toggleDevTools', label: t('toggleDevTools') },
        { type: 'separator' },
        { role: 'resetZoom', label: t('resetZoom') },
        { role: 'zoomIn', label: t('zoomIn') },
        { role: 'zoomOut', label: t('zoomOut') },
        { type: 'separator' },
        { role: 'togglefullscreen', label: t('togglefullscreen') },
      ],
    },
    {
      label: t('window'),
      role: 'window',
      submenu: [
        { role: 'minimize', label: t('minimize') },
        { role: 'zoom', label: t('zoom') },
        ...(isMac
          ? ([
              { type: 'separator' },
              { role: 'front', label: t('front') },
              { type: 'separator' },
              { role: 'window', label: t('window') },
            ] as Electron.MenuItemConstructorOptions[])
          : ([
              { role: 'close', label: t('close') },
            ] as Electron.MenuItemConstructorOptions[])),
      ],
    },
    {
      label: t('help'),
      role: 'help',
      submenu: [
        {
          label: t('learnMore'),
          click: async () => {
            const { shell } = await import('electron');
            await shell.openExternal('https://electronjs.org');
          },
        },
      ],
    },
  ];

  const menu = Menu.buildFromTemplate(template);
  Menu.setApplicationMenu(menu);
};

function registerWorkspaceIPC(): void {
  ipcMain.handle('workspace:getActive', async () => {
    const root = getActiveWorkspaceRoot();
    const meta = workspaceService.readWorkspaceMetaSync(root);
    return { path: root, meta };
  });

  ipcMain.handle('workspace:listRecent', async () => {
    return workspaceService.loadRegistry().recentWorkspacePaths;
  });

  ipcMain.handle('workspace:getDefaultPath', async () => workspaceService.getDefaultWorkspacePath());

  ipcMain.handle('workspace:remove', async (_event, folderPath: string) => {
    const res = await workspaceService.removeWorkspaceForUser(String(folderPath || ''));
    if (!res.ok) return res;
    setActiveWorkspaceRoot(res.newActivePath);
    syncClawFlowEngineWorkspaceRoot(res.newActivePath);
    BrowserWindow.getAllWindows().forEach((w) =>
      w.webContents.send('workspace:changed', { path: res.newActivePath })
    );
    void workspaceService.ensureWorkspaceInitialized(res.newActivePath);
    void getGlobalOpenClawCliEngine()
      .stopGateway()
      .catch((e) => console.warn('[workspace] stopGateway after remove (best-effort) failed:', e?.message || e));
    return res;
  });

  ipcMain.handle('workspace:setActive', async (_event, nextPath: string) => {
    const resolved = path.resolve(String(nextPath || ''));
    // Fast path: switch active workspace first (UI can update immediately).
    // Heavy operations (gateway stop, fs init) run best-effort in background.
    workspaceService.setActiveWorkspace(resolved);
    setActiveWorkspaceRoot(resolved);
    syncClawFlowEngineWorkspaceRoot(resolved);
    BrowserWindow.getAllWindows().forEach((w) => w.webContents.send('workspace:changed', { path: resolved }));
    void workspaceService.ensureWorkspaceInitialized(resolved);
    void getGlobalOpenClawCliEngine()
      .stopGateway()
      .catch((e) => console.warn('[workspace] stopGateway (best-effort) failed:', e?.message || e));
    return { success: true, path: resolved };
  });

  ipcMain.handle('workspace:pickFolder', async (event) => {
    const win = BrowserWindow.fromWebContents(event.sender);
    return await workspaceService.pickWorkspaceFolder(win);
  });

  ipcMain.handle('workspace:ensureInitialized', async (_e, folderPath: string) => {
    const meta = await workspaceService.ensureWorkspaceInitialized(String(folderPath || ''));
    return { meta };
  });

  ipcMain.handle('workspace:listDir', async (_e, relativePath?: string) => {
    const root = getActiveWorkspaceRoot();
    try {
      const entries = await workspaceExplorer.listWorkspaceDirectory(root, String(relativePath ?? ''));
      return { ok: true as const, entries };
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return { ok: false as const, error: msg, entries: [] as Array<{ name: string; kind: 'file' | 'dir' }> };
    }
  });

  ipcMain.handle('workspace:readFilePreview', async (_e, relativePath: string) => {
    const root = getActiveWorkspaceRoot();
    return await workspaceExplorer.readWorkspaceFilePreview(root, String(relativePath ?? ''));
  });

  ipcMain.handle('workspace:getChangeLog', async (_e, limit?: number) => {
    const root = getActiveWorkspaceRoot();
    const lim = typeof limit === 'number' && Number.isFinite(limit) ? limit : 100;
    const entries = await workspaceChangeLog.getWorkspaceChangeLog(root, lim);
    return { ok: true as const, entries };
  });

  ipcMain.handle(
    'workspace:appendChangeLog',
    async (_e, payload: { conversationId: string; userPreview: string; assistantExcerpt: string }) => {
      const root = getActiveWorkspaceRoot();
      try {
        const entry = await workspaceChangeLog.appendWorkspaceChangeLog(root, {
          conversationId: String(payload?.conversationId ?? ''),
          userPreview: String(payload?.userPreview ?? ''),
          assistantExcerpt: String(payload?.assistantExcerpt ?? ''),
        });
        return { ok: true as const, entry };
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : String(e);
        return { ok: false as const, error: msg };
      }
    }
  );
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    // Use a custom titlebar overlay so app icon and menus share one row (Windows).
    ...(process.platform === 'win32'
      ? {
          titleBarStyle: 'hidden',
          titleBarOverlay: {
            color: '#111315',
            symbolColor: '#c9d1d9',
            height: 44,
          },
        }
      : {}),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
      webviewTag: true,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // On Windows we hide the native menu bar row (we draw our own menus in the overlay).
  if (process.platform === 'win32') {
    mainWindow.setMenuBarVisibility(false);
    mainWindow.removeMenu();
    mainWindow.setAutoHideMenuBar(true);
  }

  // window controls for custom titlebar
  ipcMain.handle('window:minimize', (event) => BrowserWindow.fromWebContents(event.sender)?.minimize());
  ipcMain.handle('window:toggleMaximize', (event) => {
    const win = BrowserWindow.fromWebContents(event.sender);
    if (!win) return;
    if (win.isMaximized()) win.unmaximize();
    else win.maximize();
  });
  ipcMain.handle('window:close', (event) => BrowserWindow.fromWebContents(event.sender)?.close());

  // common actions (for custom titlebar menus)
  ipcMain.handle('window:reload', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.reload());
  ipcMain.handle('window:toggleDevTools', (event) => {
    const wc = BrowserWindow.fromWebContents(event.sender)?.webContents;
    if (!wc) return;
    if (wc.isDevToolsOpened()) wc.closeDevTools();
    else wc.openDevTools({ mode: 'detach' });
  });
  ipcMain.handle('window:undo', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.undo());
  ipcMain.handle('window:redo', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.redo());
  ipcMain.handle('window:cut', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.cut());
  ipcMain.handle('window:copy', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.copy());
  ipcMain.handle('window:paste', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.paste());
  ipcMain.handle('window:selectAll', (event) => BrowserWindow.fromWebContents(event.sender)?.webContents.selectAll());
  ipcMain.handle('app:quit', () => app.quit());
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(async () => {
  const reg = workspaceService.loadRegistry();
  // 如果刚执行了“取消置顶 active”的一次性迁移，这里需要写回磁盘
  if (!reg.unpinActiveMigrated && reg.activeWorkspacePath) {
    workspaceService.saveRegistry({ ...reg, unpinActiveMigrated: true });
  }
  const active = reg.activeWorkspacePath ?? workspaceService.getDefaultWorkspacePath();
  workspaceService.migrateWorkspaceOpenclawToGlobalOnce();
  workspaceService.removeLegacyWorkspaceOpenclawDirs();
  await workspaceService.ensureWorkspaceInitialized(active);
  workspaceService.setActiveWorkspace(active);
  setActiveWorkspaceRoot(active);

  registerWorkspaceIPC();
  registerOpenClawIPC();
  registerClawFlowIPC({ workspaceRoot: active, verbose: true });
  registerGatewayIPC();
  // Phase 3: keep internal GatewayDaemon resident (best-effort)
  try {
    await getGatewayDaemon().start();
  } catch (e: any) {
    console.warn('[GatewayDaemon] auto-start failed:', e?.message ?? e);
  }
  ipcMain.handle('skillMarket:getIndex', async (_e, opts?: { forceRefresh?: boolean }) => {
    try {
      return await fetchSkillMarketIndex({ forceRefresh: Boolean(opts?.forceRefresh) });
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      console.warn('[skillMarket:getIndex]', msg);
      return { ok: false as const, error: msg || 'skill market handler failed' };
    }
  });
  ipcMain.handle('app:getVersion', () => app.getVersion());
  ipcMain.handle('app:setLanguage', (_event, lang: string) => {
    currentLang = String(lang).toLowerCase().startsWith('en') ? 'en' : 'zh';
    setupApplicationMenu();
    return { success: true };
  });
  setupApplicationMenu();
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
